### ISSUE TITLE
Unable to download projects due to MinIO storage full error

### ISSUE THREAD

**Issue by rom2049** [opengisch/QFieldCloud#1001]
Hello,

While testing QFieldCloud, I added and deleted several projects. At some point, I encountered a new problem. I was no longer able to download my projects. When I checked the Jobs, I noticed the following error message:

```
An error occurred (XMinioStorageFull) when calling the PutObject operation: Storage backend has reached its minimum free drive threshold. Please delete a few objects to proceed.
```
It seems that the MinIO storage is full, possibly because objects that are no longer in use aren't being deleted ?

Thank you in advance for your help.

**Comment by rom2049** [comment]
I just checked the MinIO interface and I can confirm that all the old projects I deleted from the QFieldCloud admin interface are still stored there. Is this behavior normal ?

**Comment by suricactus** [comment]
Hello, @rom2049 . Thanks for using QFieldCloud. Unforutnately we do not provide deployment and operations support for people installing on QFieldCloud on their own hardware via GitHub. Feel free to contact us at sales [at] qfield.cloud.

If you have detected an actual replicable issue, please open a new issue.
