### ISSUE TITLE
Cloning from Github error

### ISSUE THREAD

**Issue by BizTechnology** [opengisch/QFieldCloud#1013]
Dear QFieldCloud Team,

I wanted to deploy the qfieldcloud on our server locally but I'm getting the following error when I try to clone it. Help pls:

gtg@gtg-ubuntu-server:~$ git clone --recurse-submodules git@github.com:opengisch/QFieldCloud.git
Cloning into 'QFieldCloud'...
The authenticity of host 'github.com (140.82.121.4)' can't be established.
ED25519 key fingerprint is SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU.
This key is not known by any other names.
Are you sure you want to continue connecting (yes/no/[fingerprint])? y
Please type 'yes', 'no' or the fingerprint: yes
Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Kind regards,

Biz

**Comment by suricactus** [comment]
Hello, Biz,

Thanks for trying out QFieldCloud. Seems you don't have your public key configured on GitHub. Please either configure it, or clone via http.

Best,
Ivan

**Comment by BizTechnology** [comment]
Hello GitHub Team,

Thank you for the support. I could configure and use it now. Thanks a lot.

Kind regares,
________________________________
