### ISSUE TITLE
How do i access the user portal? 

### ISSUE THREAD

**Issue by kentemman-gmd** [opengisch/QFieldCloud#1035]

**Comment by katagen** [comment]
yourdomain-name.com/admin

**Comment by kentemman-gmd** [comment]
Only the admin portal?

**Comment by suricactus** [comment]
Once you install QFieldCloud you shall be redirected to the UI login right after you access your domain name.

Nite that the GUI accessible on app.qfield.cloud is built on top of all the other functionality that is already present in QFieldCloud.
