### ISSUE TITLE
How to update the docker container?

### ISSUE THREAD

**Issue by katagen** [opengisch/QFieldCloud#1037]
I have a working docker container with qfieldcloud on a Ubuntu server, but it is the version 0.24.1!

I can't find how to update the container to the last version, without loosing all my stuff!

What are the commands I need to excecute?

**Comment by suricactus** [comment]
Hello,  @katagen . Most of the time the update process is just changing the tagged version you are using and running the required migrations. If you have more questions about your specific deployment, feel free to ask them on sales [at] qfield.cloud .
