### ISSUE TITLE
Projects fail to open after download from locally hosted QFieldCloud

### ISSUE THREAD

**Issue by BizTechnology** [opengisch/QFieldCloud#1044]
![qfield1](https://github.com/user-attachments/assets/9ab031c7-7e48-4f07-886b-57bdb1c7f504)

I'm currently facing some issues with our locally deployed QFieldCloud instance and could really use some help troubleshooting. 

I've deployed QFieldCloud on a local server and am able to upload projects from QGIS to the locally deployed QFieldCloud instance successfully. However, when trying to open projects from the QField Android and Windows apps after download of the projects to the local storage is completed, I'm getting errors.

The errors I'm seeing are:

```
Project file read error in file c:/users/bizit/appdata/roaming/opengis.ch/qfield/cloud_projects/admin/5a536cbb-a423-4835-845f-85594bcdbe34/gis4_cloud_qfield.qgs: premature end of document at line 1, column 0
Error opening zip archive: 'c:/users/bizit/appdata/roaming/opengis.ch/qfield/cloud_projects/admin/5a536cbb-a423-4835-845f-85594bcdbe34/gis4_cloud_qfield_attachments.zip' (error code: 19) 
Failed to remove temporary file gis4_cloud_qfield_attachments.zip
Failed to remove temporary file gis4_cloud_qfield.qgs
Failed to remove temporary file data.gpkg
```

Has anyone else seen these errors when downloading projects from a locally hosted QFieldCloud instance? Any suggestions on how to troubleshoot or resolve the errors would be appreciated.

**Comment by julj** [comment]
I have a similar issue: the app seems to manage to download the project, but it when opening the project I get no layers. In the log I have the same errors:

```
Project file read error in file /[data/user/0/ch.opengis.qfield/files/cloud_projects/jricard/855d35b5-7d0d-4bb2-8497-4fa71c859ea5/trees_cloud_qfield.qgs](http://data/user/0/ch.opengis.qfield/files/cloud_projects/jricard/855d35b5-7d0d-4bb2-8497-4fa71c859ea5/trees_cloud_qfield.qgs): Premature end of document. at line 1 column 0

Error opening zip archive: '/[data/user/0/ch.opengis.qfield/files/cloud_projects/jricard/855d35b5-7d0d-4bb2-8497-4fa71c859ea5/trees_cloud_qfield_attachments.zip'](http://data/user/0/ch.opengis.qfield/files/cloud_projects/jricard/855d35b5-7d0d-4bb2-8497-4fa71c859ea5/trees_cloud_qfield_attachments.zip') (Error code: 19)
```

**Comment by suricactus** [comment]
When you check the file contents, what is in there? Reading the error message, it looks like the error was not downloaded correctly. Why is that I cannot answer just from the screenshots.

Note that we do not provide official support here on GitHub for privately installed QFieldCloud, there are just too many variables (literally in `.env` file).
