### ISSUE TITLE
How can the owner of a project administrate his project ?

### ISSUE THREAD

**Issue by julj** [opengisch/QFieldCloud#1046]
I have an "admin" user with the superuser status, and a "user1" user with staff status. Using the admin user I uploaded a project from QGIS to QField Cloud, and then set "user1" as the owner of the project. Now I login to QField cloud with "user1" and get an empty admin. I would expect being able to see the projects "user1" owns, as well as the ability to add collaborators to this project.

Can a user administrate a project without being superuser ? How ? Is there any documentation for the admin page ?

**Comment by suricactus** [comment]
Hi, @julj . 

I guess you are asking how to give permissions to see the admin for that. You need to create a group that has access to projects and then assign the specific user to the group.
![image](https://github.com/user-attachments/assets/38db18f3-39a8-4d7d-a174-537eb684f5e9)
And then:
![image](https://github.com/user-attachments/assets/87c0331b-f968-4503-b648-5df587b11f8f)


The documentation how these things work in the admin:
https://docs.djangoproject.com/en/5.1/ref/contrib/admin/#django.contrib.admin.AdminSite.has_permission

Groups:
https://docs.djangoproject.com/en/5.1/topics/auth/default/#groups

Note that if your user gets access to the Project admin page, they will see all projects. This is something we are considering to work on in the future, but not planned yet. The admin API is doing handling all the permissions as they should be.
