### ISSUE TITLE
GitHub branch release not up to date

### ISSUE THREAD

**Issue by meyerlor** [opengisch/QFieldCloud#1056]
Hey,

i was really happy to see that there is a new release  (0.29) of QFieldCloud! I follow on my server the release branch and not the default master branch - this does not pull the 0.29 tagged release though, it still pulls the 0.27 one. Is there a reasaon the release branch is stale? Do you recommend using the master branch?

**Comment by suricactus** [comment]
Hey! Thanks for noticing. If you try 0.29.1 all should be good now.

**Comment by meyerlor** [comment]
great!
