### ISSUE TITLE
DuplicateObject

### ISSUE THREAD

**Issue by shapley** [opengisch/QFieldCloud#1067]
Hi,

I'm trying to create a new database connection in 'QFieldCloud admin' after deleting a previous connection. I'm now unable to enter a new 'Username' postgres because it already exists in the db. How can I remove the duplicate role 'postgres' in order to create a new connection or will it require entering the container in order to remove the role.

![duplicate_object](https://github.com/user-attachments/assets/741f5dc2-66f6-4e77-99dc-5c8cf2d218b8)

**Comment by suricactus** [comment]
It is hard to say what happened, if you provide steps to reproduce and the full error stack will greatly help.

Note that GeoDB will soon be removed from QFieldCloud and it is not recomended to be used.

I am closing this issue as it is related to a module that will be not be exposed for usage from next version onwards.
