### ISSUE TITLE
Downloading error.

### ISSUE THREAD

**Issue by shapley** [opengisch/QFieldCloud#1069]
Hi,

I get an error relating to a 'Job object' when I try to download a qgis project on my Android device.  The android device shows the error:

(Downloading error. Job(4ce74690-c0d8-423d-a850 etc...) finished with a failed status). Any idea what this may relate to? 

QFieldCloud admin > Jobs Tab

![job](https://github.com/user-attachments/assets/2f86cc43-7813-4d64-a865-9b017bc40a51)

Output pre:

[job_output_pre.txt](https://github.com/user-attachments/files/17960985/job_output_pre.txt)

Many thanks,

**Comment by suricactus** [comment]
If you read the file that you have provided, you have an error that says:
```
Requested \"http://172.16.6.131/api/v1/packages/13848d10-1fa9-4ce6-8637-f9330ca07ccf/210e57c2-e2b0-4d28-8e89-e02b5d899261/files/sam_region.gpkg/\" and got \"413 Request Entity Too Large\":\n<html>\r\n<head><title>413 Request Entity Too Large</title></head>\r\n<body>\r\n<center><h1>413 Request Entity Too Large</h1></center>\r\n<hr><center>nginx/1.26.2</center>\r\n</body>\r\n</html>\r\n
```

You have to reduce the file size in your project or increase the limits in Django and nginx.
