### ISSUE TITLE
CSRF verification failed

### ISSUE THREAD

**Issue by Mettwurscht** [opengisch/QFieldCloud#1083]
QField cloud ist locally hosted on a separate VM. Nginx on another VM works as reverse proxy and also gets the certificate by let's encrypt.

Logging in on qfield's VM by its IP adresse (http://192.168.0.5:8011) works perfectly. Accessing the domain https://qfield.example.com brings up the login interface. Logging in throws an error 403 "CSRF verification failed. Request aborted."

Further explanation is:
"Reason given for failure: Origin checking failed - https://qfield.example.com does not match any trusted origins."

At the moment, I have no idea where to place the Django option "CSRF_TRUSTED_ORIGINS".

**Comment by Mettwurscht** [comment]
Ok, found the solution. :)

Just added the following nginx configuration for the site:

````
client_max_body_size 1024M;
client_body_timeout 300s;

location / {
        proxy_pass https://192.168.0.5/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forward-Proto http;
        proxy_set_header X-Nginx-Proxy true;
        proxy_redirect off;
    }
````

**Comment by kentemman-gmd** [comment]
Do you create a default.conf file?

I tried that solution, but it is not working on my side.
