### ISSUE TITLE
Export / Download Fail when project has no features

### ISSUE THREAD

**Issue by jmad1v07** [opengisch/qfieldcloud#147]
On creating a "clean" data collection in QGIS (e.g. a GeoPackage with fields and a attributes form created but no features), it is possible to covert the project to a QFieldCloud project using the "Convert currently open project to cloud project (recommended)" OK. However, it is not possible to download this project to QField with app displaying a download error. The Jobs on QFieldCloud for the failed Export report: 

```
WARNING:QGIS_STDERR:QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
INFO:__main__:Failed to obtain the project extent from project layers.
```

However, if I create a feature in QGIS and sync with QFieldCloud all works fine. There might have been a step in project creation which I've missed here. 

@nirvn - I've added you to "simple-project" in QFieldCloud which demonstrates this in case you want to take a closer look.

**Comment by suricactus** [comment]
Hey, @jmad1v07, seems you can already download you project on your QField device? Thanks for reporting this, please reopen if you find new issues. Thanks for testing QFieldCloud.

**Comment by suricactus** [comment]
Hey, @jmad1v07, seems you can already download you project on your QField device? Thanks for reporting this, please reopen if you find new issues. Thanks for testing QFieldCloud.
