### ISSUE TITLE
Synchronizing from local to cloud fails on windows computer but works on Linux mint 

### ISSUE THREAD

**Issue by BoswachterMarc** [opengisch/qfieldcloud#151]
Strange issue, synchronizing (from local to cloud) from a windows 10 Enterprise pc is a problem since yesterday evening. But it works from cloud to local.

Synchronizing from a linux Mint 20 xfce 64-bit works in both ways.
I thought, perhaps it is an issue because of some geometry changes I made on the windows side, so I synchronized back from linux Mint to cloud and then on the windows pc from cloud to local (I lost the geometry changes). This worked out well. Then making on change on windows side again en syncing back from local to cloud, syncing is aborted again.

Each time I got a time-out message, without any difference trying to sync all changes (*.qgs and *.gpkg files) at once or one for one.

![image](https://user-images.githubusercontent.com/57868975/142292469-b0fa8d29-339f-4dce-bc14-58a3ae5b78ba.png)
![image](https://user-images.githubusercontent.com/57868975/142292510-5c13149c-e606-499e-abae-9678c80e33a8.png)
![image](https://user-images.githubusercontent.com/57868975/142292694-1eaec318-50ad-44d5-9e20-888b3aa80157.png)
![image](https://user-images.githubusercontent.com/57868975/142292778-c1b25f29-3c5c-4f73-9672-86dc41e45f37.png)

**Comment by BoswachterMarc** [comment]
Still having the same problem; at first, synchronizing goes fast but then freezes... Finally, there is a time out.

![image](https://user-images.githubusercontent.com/57868975/143299878-4574e42c-cc68-4f8d-b5f0-ae3bb8b192bd.png)

**Comment by suricactus** [comment]
There is indeed a timeout issue if the project fails to be uploaded in 60 seconds. This has been addressed and will be release very soon both on QFieldSync and QFieldCloud.

The second issue:
> Still having the same problem; at first, synchronizing goes fast but then freezes... Finally, there is a time out.
unfortunately is a QT issue (QT is the framework behind QGIS) outside QFieldSync control. The upload bar does not show what is really sent to the server, but what QT has buffered for sending. This is quite annoying but failed to find any workaround so far.

**Comment by suricactus** [comment]
The timeouts have been raised at maximum, so trying app.qfield.cloud with QFieldSync 4.0.0 BETA20 should fix the issue. Please open a new issue if it still not working.
