### ISSUE TITLE
Duplicate Deltas

### ISSUE THREAD

**Issue by jmad1v07** [opengisch/qfieldcloud#154]
Hi, we're seeing duplicate_deltafile server error when trying to synchronise or push commits from QField and is preventing projects from syncing and uploading new data to QFieldCloud. 

This behaviour is happening across multiple devices (but not all devices pushing data to the project on QFieldCloud). 

On QFieldCloud the project has all conflicts resolved (i.e. status is project synced). 

Is there a way to handle this from within QField or to regenerate a deltafile id on the device? Or, is there a way to remove the deltafile with the clashing id from QFieldCloud to allow data on devices to sync?

Relatedly, is there a better option than `adb backup -noapk xxxx` for retrieving data from QFieldCloud projects that are prevented from syncing as a back up in cases like this? 

Please let me know if I can provide anymore info or if this should be moved to Discussions. Thanks!

![Screenshot_2021-11-23-19-35-23-64_2e601d870d31f598a7096b1e53961eb8~2](https://user-images.githubusercontent.com/20630310/143056050-9e31e361-03d2-4bf8-9974-630c156e76f0.jpg)

**Comment by suricactus** [comment]
This will be fixed with the next relase of QFieldCloud.
