### ISSUE TITLE
how to delete my project on the cloud?

### ISSUE THREAD

**Issue by SerhiyKSV** [opengisch/qfieldcloud#157]
I have created several test projects that I do not use. How can I delete a project on the cloud that I don't need?

**Comment by jmad1v07** [comment]
Hi @SerhiyKSV - there is an option to delete projects on QFieldCloud under the project's settings if you're using the hosted version.

**Comment by suricactus** [comment]
Closed as it is answered. Please check the discussion board here too: https://github.com/opengisch/qfieldcloud/discussions/161
