### ISSUE TITLE
cannot upload local QfieldSync directory

### ISSUE THREAD

**Issue by MMR100** [opengisch/qfieldcloud#185]
I have a bug when trying to convert a project into cloud project

When I want to convert currently open project to cloud project, if I use the button with three dots, then select one folder in my computer, I have a message saying that "The entered path does not contain a QGIS project file yet" then I click "ok" and it send me back to the folder selection (see image below)

![cannot upload local QfieldSync directory](https://user-images.githubusercontent.com/26409106/146552152-6028460c-9d97-4580-b63b-c8b6bc073260.png)

However, if I write the folder path by hand instead of using the three dots button, then the button "create" become enabled. 

![manual entry of the directory](https://user-images.githubusercontent.com/26409106/146552978-2e611ac1-6690-4547-8605-90616b41b7bf.png)

**Comment by suricactus** [comment]
Thanks for reporting @MMR100 ! Yes, it was recently discovered in the latest BETAs that we have this problem. It will be addressed with the upcoming QFieldSync BETA18

**Comment by suricactus** [comment]
> I have a bug when trying to convert a project into cloud project
> 
> When I want to convert currently open project to cloud project, if I use the button with three dots, then select one folder in my computer, I have a message saying that "The entered path does not contain a QGIS project file yet" then I click "ok" and it send me back to the folder selection (see image below)
> 
> ![cannot upload local QfieldSync directory](https://user-images.githubusercontent.com/26409106/146552152-6028460c-9d97-4580-b63b-c8b6bc073260.png)
> 
> However, if I write the folder path by hand instead of using the three dots button, then the button "create" become enabled.
> 
> ![manual entry of the directory](https://user-images.githubusercontent.com/26409106/146552978-2e611ac1-6690-4547-8605-90616b41b7bf.png)
