### ISSUE TITLE
Documentation doesn't succeed

### ISSUE THREAD

**Issue by stcz** [opengisch/qfieldcloud#211]
Thanks for the great project. I want to take a closer look at it and followed the instructions on the README.

I created a new Ubuntu 20.04 VM, installed `docker-compose` and checkout the master branch of this repository and followed the instructions.

The first error I receive is:
```
invalid sslmode value: "prefer # "prefer" OR "require" most of the times"
```
I solved this by removing the comment in `.env`.

Further I get:
```
ERROR: The Compose file './docker-compose.override.yml' is invalid because:
services.createbuckets.depends_on contains an invalid type, it should be an array
```
Referring to the [documentation](https://docs.docker.com/compose/compose-file/compose-file-v3/#depends_on), the depends_on condition is not supported anymore in docker-compose 3.x. I fixed this with:
```
--- docker-compose.override.local.yml   2022-01-03 18:36:06.136000000 +0000
+++ docker-compose.override.yml 2022-01-03 18:43:10.536000000 +0000
@@ -102,8 +102,7 @@
   createbuckets:
     image: minio/mc
     depends_on:
-      minio:
-        condition: service_healthy
+      - minio
     entrypoint: >
       /bin/sh -c "
       /usr/bin/mc config host add myminio ${STORAGE_ENDPOINT_URL} ${STORAGE_ACCESS_KEY_ID} ${STORAGE_SECRET_ACCESS_KEY};

```
After these changes the containers are built and running.

Then I'm able to access the WebUI and it seems working.

But if I'm running the tests (got this from [github workflows](https://github.com/opengisch/qfieldcloud/blob/master/.github/workflows/test.yml)):

```
docker-compose run app python manage.py test -v2 qfieldcloud
```
They will fail:
```
...
FAIL: test_change_and_delete_pushed_only_features (qfieldcloud.core.tests.test_delta.QfcTestCase)
FAIL: test_list_all_deltas_and_list_deltas_by_deltafile (qfieldcloud.core.tests.test_delta.QfcTestCase)
FAIL: test_non_spatial_delta (qfieldcloud.core.tests.test_delta.QfcTestCase)
FAIL: test_push_apply_delta_file (qfieldcloud.core.tests.test_delta.QfcTestCase)
FAIL: test_push_apply_delta_file_conflicts_overwrite_false (qfieldcloud.core.tests.test_delta.QfcTestCase)
FAIL: test_push_apply_delta_file_conflicts_overwrite_true (qfieldcloud.core.tests.test_delta.QfcTestCase)
FAIL: test_push_apply_delta_file_twice (qfieldcloud.core.tests.test_delta.QfcTestCase)
FAIL: test_push_apply_delta_file_with_error (qfieldcloud.core.tests.test_delta.QfcTestCase)
FAIL: test_push_list_deltas (qfieldcloud.core.tests.test_delta.QfcTestCase)
FAIL: test_push_list_multidelta (qfieldcloud.core.tests.test_delta.QfcTestCase)
FAIL: test_download_file_for_qfield (qfieldcloud.core.tests.test_packages.QfcTestCase)
FAIL: test_download_project_with_broken_layer_datasources (qfieldcloud.core.tests.test_packages.QfcTestCase)
FAIL: test_downloaded_file_has_canvas_name (qfieldcloud.core.tests.test_packages.QfcTestCase)
FAIL: test_filename_with_whitespace (qfieldcloud.core.tests.test_packages.QfcTestCase)
FAIL: test_list_files_for_qfield (qfieldcloud.core.tests.test_packages.QfcTestCase)
FAIL: test_download_file_for_qfield (qfieldcloud.core.tests.test_qfield_file.QfcTestCase)
FAIL: test_download_project_with_broken_layer_datasources (qfieldcloud.core.tests.test_qfield_file.QfcTestCas
e)
FAIL: test_downloaded_file_has_canvas_name (qfieldcloud.core.tests.test_qfield_file.QfcTestCase)
FAIL: test_filename_with_whitespace (qfieldcloud.core.tests.test_qfield_file.QfcTestCase)
FAIL: test_list_files_for_qfield (qfieldcloud.core.tests.test_qfield_file.QfcTestCase)
FAILED (failures=20)
...
```
I attached the complete [test.log](https://github.com/opengisch/qfieldcloud/files/7804101/test.log)

I tried to sync a project within the Test instance (exposed in a Local Network) but this also didn't work.

I didn't spend that much time up to now investigating the Errors, because i'm thinking this should not happen at a new setup. Or is it maybe related to my changes in the other files?

Thanks for your help.

**Comment by suricactus** [comment]
Thanks for the feedback, much appreciated! I can have a deeper look later this month, but from first glance it seems the problem is not in you.

The `.env` problem is aknowledged and I am looking for a workaround. If you know about an easy way to parse `.env` file in `bash`, would be much appreaciated.

As for docker-compose syntax error, feel free to open a PR.

On the tests, I guess the problem is not directly related to you.

**Comment by suricactus** [comment]
Thanks for the fixes!

**Comment by stcz** [comment]
Is there anything new about the failing Unittests?
For me they are now 23 failing
[test.log](https://github.com/opengisch/qfieldcloud/files/8355117/test.log)

**Comment by suricactus** [comment]
There were new environment variables added, please check if you properly configured them in your own `.env` file.
