### ISSUE TITLE
Issue with downloading project to device

### ISSUE THREAD

**Issue by GetBack2Basics** [opengisch/qfieldcloud#295]
When I try to download a qgisfieldcloud project I get the following errors.

1.Not packaged correctly
2. Invalid data provider

Project is fine is a cable downloaded project using QField sync.
.
Data is in 28355
![Screenshot_2022-03-12-22-11-33-356](https://user-images.githubusercontent.com/17077850/158017667-62d4bab8-fffb-40fa-8b57-31aeeb212bb0.jpg)

-------
Log from admin console
```
<<<::12e3312f-1de9-4e80-b54a-3ed9bcca8ef4 Download Project Directory
INFO:root:Downloading file "projects/473e9e36-21b0-4085-8954-51015f680343/files/Base_Data.gpkg", size: 225402880 bytes, md5sum: "57d62855a93e679778c0e68736a0d380-27" 
INFO:root:Downloading file "projects/473e9e36-21b0-4085-8954-51015f680343/files/Community_Mapping_qfield.qgs", size: 1126958 bytes, md5sum: "51b4085209b459bd246295214c3506ee" 
INFO:root:Downloading file "projects/473e9e36-21b0-4085-8954-51015f680343/files/Conservation_Species_Vernacular.csv", size: 7986 bytes, md5sum: "bc03b28c398fc98805114dab5882b9c1" 
INFO:root:Downloading file "projects/473e9e36-21b0-4085-8954-51015f680343/files/Team.csv", size: 83 bytes, md5sum: "10c05c35e7e5b110fcb582cd19f57477" 
::>>>::12e3312f-1de9-4e80-b54a-3ed9bcca8ef4 2
::<<<::c260485e-ac08-4a66-8e5c-4b4d4d8eaa50 Project Validity Check
INFO:root:Check QGIS project file validity...
::>>>::c260485e-ac08-4a66-8e5c-4b4d4d8eaa50 2
::<<<::f5b1a6ab-44d8-4373-bab8-ed6b4a9a197d Opening Check
INFO:root:Open QGIS project file...
INFO:QGIS_STDERR:Starting QGIS app version 32203 (exported)...
WARNING:QGIS_STDERR:QStandardPaths: XDG_RUNTIME_DIR points to non-existing path '/run/user/0', please create it with 0700 permissions.
WARNING:QGIS_MSGLOG:Cannot open Z:/My Drive/Mangoesmapping/Spatial Projects/2022/002_TRC_Community_Mapping/Working/QField/Base_Data.gpkg.()
WARNING:QGIS_MSGLOG:Cannot open Z:/My Drive

WARNING:QGIS_MSGLOG: * Z:/My Drive/Mangoesmapping/Spatial Projects/2022/002_TRC_Community_Mapping/Working/Data_Editable.gpkg|layername=Record_a_place
WARNING:QGIS_MSGLOG: * Z:/My Drive/Mangoesmapping/Spatial Projects/2022/002_TRC_Community_Mapping/Working/Data_Editable.gpkg|layername=Record_an_area
WARNING:QGIS_MSGLOG: * Z:/My Drive/Mangoesmapping/Spatial Projects/2022/002_TRC_Community_Mapping/Working/Team.csv
WARNING:QGIS_MSGLOG: * Z:/My Drive/Mangoesmapping/Spatial Projects/2022/002_TRC_Community_Mapping/Working/QField/Base_Data.gpkg|layername=Watercourse
WARNING:QGIS_MSGLOG: * Z:/My Drive/Mangoesmapping/Spatial Projects/2022/002_TRC_Community_Mapping/Working/Base_Data.gpkg|layername=Roads and Tracks
::>>>::3d3d347f-a6bf-464f-b5df-0b3185c0a108 2
INFO:QGIS_STDERR:Stopping QGIS app...
Feedback pre:
{
```

**Comment by suricactus** [comment]
@GetBack2Basics From the logs you have posted it seems your project has absolute paths to files that are not accessible on QFieldCloud. Please make sure your .qgs project contains only relative paths and you upload the referenced files correctly to QFieldCloud.

**Comment by GetBack2Basics** [comment]
I thought QFieldCloud required absolute paths - I tried again with relative but still get the same message - will add full error log to the folder. The project and data is downloadable from - https://drive.google.com/drive/folders/1pFDh5yPQG6ZDE1WHor0PEWL_m9vjsb5o

**Comment by suricactus** [comment]
@GetBack2Basics thanks for checking the documentation. However, there is a context to the section you are pointing to. It says the local directory path should be configured as absolute path, not the project configuration:

![image](https://user-images.githubusercontent.com/2820439/158140185-044042d6-cc7e-4729-b2d4-63e749b8778e.png)

I have tried you project and indeed you have configured it to use absolute path for datasource:
![image](https://user-images.githubusercontent.com/2820439/158140667-128fa545-45bc-4277-8bc6-f6ed52ea54be.png)
![image](https://user-images.githubusercontent.com/2820439/158140403-0ca457d2-5c9c-4b20-b65d-037695ad1425.png)

You have never mentioned what is the QFieldSync version you are using, but it is definitely not the latest one. It will forbid you from uploading your project with a message like:
![image](https://user-images.githubusercontent.com/2820439/158140321-0235b3bc-876f-4ea5-a04c-de41d7f2d5df.png)

**Comment by GetBack2Basics** [comment]
Thanks. It seems as if simply changing the properties from Absolute to Relative in QGIS doesn't work. I had to delete the old sources and rebuild the project. 

After that it worked. 

Sorry for not understanding the Relative paths are required for QFieldCloud. It is clear that this is a requirement for QFieldSync but I guess I was confused by this section of the documentation for Cloud.

**Comment by suricactus** [comment]
Glad to hear it worked!

Yes, simply changing the setting to "relative paths" would not work, as the `.qgs` project file already stores them as absolute.

The confusion from the documentation is noted, there will be changes in the docs soon and I will try to take your feedback into account.
