### ISSUE TITLE
No Information about failed Jobs on Webpage

### ISSUE THREAD

**Issue by stcz** [opengisch/qfieldcloud#313]
I have some failed jobs in my qfield cloud under the jobs tab.
![Jobs](https://user-images.githubusercontent.com/66465573/163613747-e297b030-c581-40ba-817a-43f5c090d75e.png)

On succeeded jobs I'm able to click on the Job ID to receive more details.

On failed jobs I'm not able to click on the Job ID, and so I'm not able to receive details what went wrong.

To investigate the cause, it would be great to receive more details about the failures.

Thanks for your work.

**Comment by suricactus** [comment]
The reason why there are no logs available is that... well, no logs were available for these jobs. There is not much that can be done, probably we can just add "no logs available".

**Comment by stcz** [comment]
Thank you for this answer.

On my point of view, it looks like the outage from 16. April was caused because the deltas were not applied by the corresponding service that is doing this.
I had no indication when looking for the cause of the failure. For a user, it would be great to see what happens and why the job failed. 

Has the System the ability to receive even more details as "no logs available"? For Example, "Job could not start because of a Server Error" or anything else that could happen?

For a user it would be great to determine if the error is caused by the server, that i can open a ticket, or the error is caused by me, and i have to act by myself.

**Comment by suricactus** [comment]
> Has the System the ability to receive even more details as "no logs available"? For Example, "Job could not start because of a Server Error" or anything else that could happen?

This is what I meant. Until this is implemented, you can safely assume there was a server error if the logs are missing.

If the error is caused by the user, it would be shown in the logs.
