### ISSUE TITLE
Unable to synchronize, changes stay in "pending" status

### ISSUE THREAD

**Issue by stcz** [opengisch/qfieldcloud#314]
A few days ago, the synchronization of our two QField cloud projects stopped working. The projects are owned by one account and shared to three others, which are each logged in on one Android device. App versions are 2.0.9 on two and 2.0.14 on the third device.

The failure to synchronize makes itself evident by the synchronization running endlessly on the Android devices when there are local changes (hangs at the stage "QFieldCloud is applying the latest uploaded changes. This might take some time, please hold tight."). Alternatively, on QField 2.0.14, the synchronization sporadically also aborted with a message "Data failed to reach QField cloud" (without further information).

Pushing the changes instead of synchronizing the project results in a success message. Subsequent synchronization attempts after the push also terminate without error. However, rather than updating the data set, the synchronization in this case results in the previously pushed local changes to go missing and thus to data loss.

On QFieldCloud's web interface, the changes we attempted to synchronize do appear in the "Changes" view with status "Pending". Trying to apply them manually yields the message "x change(s) will be applied". However, even after several hours, they are still not applied. The corresponding Jobs are failing without any output (#313).

I hope this description provides a suitable starting point for an analysis of the problem. Of course, we are happy to provide additional details and the IDs of/access to the projects in question, in case this is helpful.

**Comment by suricactus** [comment]
We are already aware of the problem and workig on it, fix is coming early next week. Thanks for reporting.

**Comment by suricactus** [comment]
@stcz  @cedridmondy @marius851000 @enheduanna Can you please try to manually apply your changes now? Hopefully all should work as expected.

**Comment by CedricMondy** [comment]
@suricactus it seems to work for me now, thank you very much!

**Comment by Indiok** [comment]
thank you, now i can aply data but when sincronizing at my computer nothing changes, not seem normal like before

**Comment by stcz** [comment]
For me everything looks fine in QGIS and QField.. :) Thank you very much!

**Comment by enheduanna** [comment]
Dear Ivan
Yes, it worked - I had pushed the changes on the 16th of April and I just
sync and they have all been applied with a couple data points missing. Than
you so much for letting us know and for looking into this.
Best wishes
Stephanie aka enheduanna

**Comment by JHL99** [comment]
Success with my data also.

'Pending Changes'  where successfully manually applied to master data.  Also, new data pushed from mobile device did not get stuck in 'pending changes' and was nearly immediately absorbed into master data.

Thanks for the fast respnose.

JHL99
________________________________

**Comment by suricactus** [comment]
Very happy to hear it worked well for all of you. Thanks for testing and ringing the bell for QFieldCloud during it's beta phase. Your feedback is invaluable!

**Comment by Indiok** [comment]
thanks a lot @suricactus , in my testing project now can work sincronize normally :)

**Comment by alexhogan18** [comment]
Im still having issues syncing, data goes missing on the app when syning, however the data has been pushed into the project when looking at the project in chrome and on qgis

**Comment by suricactus** [comment]
@alexhogan18 please open a new issue with a sample project and all the details you can provide about your issue.

**Comment by alexhogan18** [comment]
@suricactus I just posted a new question on the discussion board with more details, hopefully it outlines my issues a bit better
