### ISSUE TITLE
Error pushing changes

### ISSUE THREAD

**Issue by antoniusz** [opengisch/qfieldcloud#327]
I'm getting these error, when trying to push changes from qfield.

Failed to upload delta file, reason:
Error transferring
https://app.qfield.cloud/api/v1/deltas/1864d519-8fd9-425c-abc5-4ab97c9fd617/
- server replied: Internal Server Error
[QF/]

[QF/]
[HTTP/500]
https://app.qfield.cloud/api/v1/deltas/1864d519-8fd9-425c-abc5-4ab97c9fd617/
Server Error.{"code":["unknown_error"],"message":["QFieldcloud Unknown
Error"]}
{"code":["unknown_error"],"message":["QFieldcloud Unknown Error"]}
Error transferring
https://app.qfield.cloud/api/v1/deltas/1864d519-8fd9-425c-abc5-4ab97c9fd617/
- server replied: Internal Server Error

**Comment by suricactus** [comment]
@antoniusz did you try in the last 60 mins? There was a maintanance period that we were aware of the 500 errors. Can you try again and share the result?

**Comment by antoniusz** [comment]
I have the same error messages.

**Comment by suricactus** [comment]
Yup, I got it. There is a strange unicode sequence that is rejected by the server. Will investigate.

**Comment by suricactus** [comment]
Somehow you managed to enter a `\u0000` in the string. Thank you for reporting, I will sanitize the string and the fix will come with the next server upgrade.

**Comment by antoniusz** [comment]
It should be something wrong with the project files, because I'm getting the same error on different devices.

**Comment by antoniusz** [comment]
The problem is gone.
