### ISSUE TITLE
Collaborators and Teams: UI Obscurred

### ISSUE THREAD

**Issue by miili** [opengisch/qfieldcloud#364]
Hi all,

the experience adding user and teams could be improved by better auto suggestions. Also the `input` is obsurred by firefox' auto completion `View saved Logins`. The `<input ... name=username .../>` is the problem. 

![image](https://user-images.githubusercontent.com/4992805/178240736-accc90a0-d6b5-46c6-be5a-346c7f9cef7a.png)

**Comment by suricactus** [comment]
Turns out that browsers are super stubborn on showing this autofill suggestions.

Finally found a solution here:
https://gist.github.com/niksumeiko/360164708c3b326bd1c8
