### ISSUE TITLE
How to increase the limit on number of collaborators

### ISSUE THREAD

**Issue by jitendrashahiitb** [opengisch/qfieldcloud#401]
How do I increase the number of collaborators? 
I have tried to register for 'Pro' version but it does not work as it says it is free till it is Beta version
What is the way out? I am trying to popularise qfield to college students in thousands. 
So need to add collaborators

**Comment by suricactus** [comment]
Please check my comments here https://github.com/opengisch/QField/discussions/3204 and here https://github.com/opengisch/QField/discussions/3206 , which I believe answer your question.
