### ISSUE TITLE
Account Name: Environment Variable for QFieldCloud Username

### ISSUE THREAD

**Issue by miili** [opengisch/qfieldcloud#410]
How can one get hold of the username?

There should be a variable like `@qfieldcloud_username` to track the responsible editor.

**Comment by nirvn** [comment]
@miili , there is: @cloud_username

**Comment by miili** [comment]
Great, where is this documented?

**Comment by suricactus** [comment]
It is not yet, but there are multiple question on GitHub discussions about this.
