### ISSUE TITLE
permission error when synchronising

### ISSUE THREAD

**Issue by robibrazze** [opengisch/qfieldcloud#412]
Hi,
when synchronising my qgis project, the following error message appears.
Version qgis:  3.16.5
Version plugi qfield: last 
any suggestions?
thanks 

PermissionError: [WinError 5] Accesso negato: 'C:\\Users\\geomb\\Documents\\UFFICIO\\COMMESSE MAPPE\\016-35-Savigliano\\qfield_esempio\\cloud_1\\.qfieldsync\\backup' 
Traceback (most recent call last):
  File "C:\Users/geomb/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\gui\cloud_transfer_dialog.py", line 253, in 
    reply.finished.connect(lambda: self.prepare_project_transfer())
  File "C:\Users/geomb/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\gui\cloud_transfer_dialog.py", line 343, in prepare_project_transfer
    self.project_transfer = CloudTransferrer(
  File "C:\Users/geomb/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\core\cloud_transferrer.py", line 87, in __init__
    shutil.rmtree(self.temp_dir)
  File "C:\PROGRA~1\QGIS31~1.15\apps\Python39\lib\shutil.py", line 740, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\PROGRA~1\QGIS31~1.15\apps\Python39\lib\shutil.py", line 613, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\PROGRA~1\QGIS31~1.15\apps\Python39\lib\shutil.py", line 622, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\PROGRA~1\QGIS31~1.15\apps\Python39\lib\shutil.py", line 620, in _rmtree_unsafe
    os.rmdir(path)
PermissionError: [WinError 5] Accesso negato: 'C:\\Users\\geomb\\Documents\\UFFICIO\\COMMESSE MAPPE\\016-35-Savigliano\\qfield_esempio\\cloud_1\\.qfieldsync\\backup'

Versione Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Versione di QGIS: 3.16.15-Hannover Hannover, e7fdad64 

Percorso Python:
C:/PROGRA~1/QGIS31~1.15/apps/qgis-ltr/./python
C:/Users/geomb/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/geomb/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS31~1.15/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS31~1.15\bin\python39.zip
C:\PROGRA~1\QGIS31~1.15\apps\Python39\DLLs
C:\PROGRA~1\QGIS31~1.15\apps\Python39\lib
C:\PROGRA~1\QGIS31~1.15\bin
C:\PROGRA~1\QGIS31~1.15\apps\Python39
C:\PROGRA~1\QGIS31~1.15\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS31~1.15\apps\Python39\lib\site-packages\GDAL-3.4.0-py3.9-win-amd64.egg
C:\PROGRA~1\QGIS31~1.15\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS31~1.15\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS31~1.15\apps\Python39\lib\site-packages\Pythonwin
C:/Users/geomb/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users/geomb/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web
C:\Users\geomb\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
C:/Users/geomb/Documents/UFFICIO/COMMESSE MAPPE/016-35-Savigliano/qfield_esempio/cloud_1

**Comment by suricactus** [comment]
Hi @robibrazze . It seems there is a permission error. The current windows user that started QGIS cannot use the files within `C:\Users\geomb\Documents\UFFICIO\COMMESSE MAPPE\016-35-Savigliano\qfield_esempio\cloud_1\.qfieldsync`. What you can do is to guarantee the current user has write permissions in you `C:\Users\geomb\Documents\UFFICIO\COMMESSE MAPPE\016-35-Savigliano\qfield_esempio\cloud_1` directory. To fix the current issue, try change the ownership of the files within that directory or if you can't - delete you can safely delete them and start over. Try also different locations on your computuer, e.g. `C:` and if available `D:`.

If this does not help, try running QGIS as administrator for the sake of experiment. The problem should be gone and it just confirms the solution is within the first paragraph.
