### ISSUE TITLE
Jobs: Timeout error - 60 s too short - Changes are not applied

### ISSUE THREAD

**Issue by miili** [opengisch/qfieldcloud#416]
Jobs on `Eifel-Large-N/Eifel_LargeN-Deployment` are running into a timeout error.

It looks like the deltas are too many.

```
Timeout error! The job failed to finish within 60 seconds!
```

See job e.g. `50f8b8b2 `

60 seconds timeout is too short for the running job to finish.

**Comment by suricactus** [comment]
Thansk for pointing this out. It is a regression from 10 minutes to 1 minute during the update 2 days ago. Now itis increased back to 10 minutes and should be good.

**Comment by miili** [comment]
Excellent, the project is assembling again!
