### ISSUE TITLE
Error downloading to phone

### ISSUE THREAD

**Issue by jomejia** [opengisch/qfieldcloud#439]
Job message

Package (b5962afe-12e9-4ee1-a192-e64dd4915846)

> Start QGIS Application ok
> Download Project Directory ok
> QGIS Layers Data ok
Package Project X
16:52:21.742 QGSSTDERR WARNING QFSFileEngine::open: No file name specified
16:52:21.743 QGSSTDERR INFO Stopping QGIS app…

**Comment by suricactus** [comment]
You have some kind of problem with the area of interest. Cannot investigate deeper now, but just either make it blank, or set it to proper value. Configuration is from QFieldSync.
