### ISSUE TITLE
getting server not found error while running qfieldcloud on docker-compose

### ISSUE THREAD

**Issue by amitabhajana** [opengisch/qfieldcloud#463]
Hi 

I have deployed a qfieldcloud instance using docker-compose. But when trying to open this application in web browser i am getting 
```
 The requested resource was not found on this server.
``` 
 But i can open the django admin and open-api portal perfectly. Error screenshots are attatched.
![Screenshot from 2022-12-19 17-13-39](https://user-images.githubusercontent.com/70099241/208419188-1aecb12b-5aae-4226-87ae-858b5a304475.jpg)

**Comment by cwillmes** [comment]
Hi,

I have the same issue. I am not so experienced using docker, is this maybe a docker config issue?
Or is the base qfieldcloud web app not part of the docker installation as described here: https://github.com/opengisch/qfieldcloud/blob/master/README.md ?
Api, admin, etc all working fine...

Can also successfully connect to that server from qfield android and QGIS plugin.

Thanks very much for any hints.

![Bildschirmfoto vom 2023-02-01 13-40-58](https://user-images.githubusercontent.com/289586/216046205-74e4eea7-ba97-4116-8076-10bde954a034.png)

**Comment by suricactus** [comment]
You can find all these services in this docker compose:
- Admin web UI endpooint
- JSON API endpoint
- API documentation
- user authentication
- user authorizatio
- subscription management

In short, if you see the admin page and can connect from QField/QFieldSync/Python SDK, then you succefully started QFieldCloud. Hope it helps @cwillmes @amitabhajana .

**Comment by cwillmes** [comment]
Thanks,
But the problem or the question was about the qfieldcloud web app, for registering accounts or editing projects, etc..
Is this web app part of the docker install or not? If yes, how to configure docker to be able to access it.
Thanks.

**Comment by suricactus** [comment]
The Web UI app is not open sourced.
