### ISSUE TITLE
Synchronizing Orthofotos failing

### ISSUE THREAD

**Issue by meyerlor** [opengisch/qfieldcloud#471]
Hello,

My orthofotos are not getting synced to my tablet. I was following your (deprecated) guide and created the raster data within an Geopackage. The project's data is split into two geopackages: One for the orthofoto, one for vector data. the orthofoto.gpkg ist ~1.3GB

It took several attempts to upload the DOP into the cloud, but then it succeeded. Getting the project now synced to the tablet seems to fail, no matter how often i try (tablet is in Wifi and we have quite fast internet)

JobID (packaging) is: 7a4a5e50 

It is failing at the last step "Upload Packaged Project"

```
Upload Packaged Project
12:39:15.770 root      INFO     Local files list for project "af2c5803-a85b-4d0a-b0ae-0eaeb449743f":
Name                                              Size  MD5 Checksum
------------------------------------------  ----------  --------------------------------
Wolpertswende_cloud_qfield.qgs                 2125189  6b4521d559beb52d725f5ba6524889bb
Wolpertswende_cloud_qfield_attachments.zip        1125  a3bfcbc611d6e2e69a06b3932c56c5f0
Wolpertswende_raster.gpkg                   1383251968  f13aabb481e5dee0badee2b2771550ba
data.gpkg                                     18235392  deefb056dcbe68bdf50986af31a2062e
12:39:15.773 root      INFO     Uploading file "data.gpkg"…
12:39:18.825 root      INFO     Uploading file "Wolpertswende_raster.gpkg"…
Killed
```

Is there a maximum file size? Or what could be the mistake?

**Comment by suricactus** [comment]
QFIeldCloud workers are limited to 2GB of memory. Your orthophoto makes QGIS running on QFIeldCloud to use more than 2GB of memory, therefore kills the process.

There are few potential optimizations that can improve the situation, but you can expect them in the Q2 or later this year.

My current recommendation is just to avoid GB big datasets without using an online service like WFS/WMS.

**Comment by meyerlor** [comment]
Thanks for the fast answer!

Alright, noted. I'm trying to optimize the file size and trying with COG now. Or would it be an possible solution to sync the vector data of the project via cloud and place the DOP manually via cable in the right folder? (it does not need to be synced on a regluar base anyway)

**Comment by suricactus** [comment]
If you can find some optimal values, would be great to share here with the greater community!

I guess this should work for you https://docs.qfield.org/how-to/outside-layers/ .

**Comment by meyerlor** [comment]
sorry for adding another comment here, i'm trying your suggested solution and followed the steps closely. Unfortunately, syncing the project with a localized raster does not work via the cloud. I'm getting the following error message:
![grafik](https://user-images.githubusercontent.com/15894401/212028019-600357cb-fc0c-47db-a5d6-f573137d45dc.png)

To check if it is correctly done on my side I copyied the project folder manually into the Qfield folder on the device (the DOP is _only_ in the basemap folder) an voila, it correctly loads the raster. Should I open another issue here? Not sure if it's a Qfield Cloud, Qfield or QField-Sync issue.

I tried it with a COG and a raster within a GeoPackage.

**Comment by suricactus** [comment]
@meyerlor ah, sorry I forgot that we made QFieldSync more restrictive to prevent users from accidentally forgetting uploading the external dataset. 

One final try, which I don't promise will work. You can try uploading your project using https://github.com/opengisch/qfieldcloud-sdk-python , there are no such checks. Currently I don't have the resources to try it myself, but there is high chance that QFieldCloud complains about the layers too.

If you want, feel free to contact us on info at opengis.ch.

BTW showing the full current window on you screenshots helps getting the context, I assume you saw this in QFieldSync.

**Comment by meyerlor** [comment]
@suricactus thanks for getting back to me. I think the python-sdk is above my ability, at least for this week i can not try this out, but i eventually will do!

Will it either be possible to add larger (raster)datasets to a project or use the localized-data approach, once QfieldCloud is not in Beta anymore? We are definately aiming for Organization-level account.
I just saw you updated the price policy on qfield.cloud - to save storage, the localized approach would be much preferred! ;)

The screenshot was actually taken from Qfield, on QGIS/QFieldSync as well as on the "Jobs" overview via the web interface of QfieldCLoud, no error messages showed. Sorry for not mentioning that!
