### ISSUE TITLE
QField Cloud No Longer Syncing Point Geometries

### ISSUE THREAD

**Issue by DColby-UMS** [opengisch/qfieldcloud#472]
Just experienced an issue and it's fairly new.  It just started happening recently and I think it may be due to a recent update of the QField application.  When capturing points on the qfield application and syncing it to the cloud and accessing it via QGIS, the point geometries are no longer syncing to QGIS, however the feature attributes and attachments (photos) are coming across in the layer attribute table, but with no associated point feature on the map.   The data on the QField Application is displaying the collected points just fine.  Line geometries are working fine btw.  Another side note.. There have been no changes in the project configuration.   It has been working fine, until just recently within the last week.
Is anyone else experiencing this?

**Comment by suricactus** [comment]
Can you share a bit more details with your username and project, so we can investigate the logs? Also which QField and device you are using.

**Comment by DColby-UMS** [comment]
Thanks suricatus..  Let me get with my team and see if we can get you access.  I think I have your email, so I may send it that way.

**Comment by DColby-UMS** [comment]
> Can you share a bit more details with your username and project, so we can investigate the logs? Also which QField and device you are using.

Can you send paste your email and we can invite you as a collaborator?

**Comment by DColby-UMS** [comment]
Update:  FYI - We found a workaround for now...  We uninstalled the latest release 2.60 and installed the previous version 2.57 and now the geometries are coming across fine.  Definitely, something going on with the latest release.

**Comment by suricactus** [comment]
@DColby-UMS this should be fixed starting from last Sunday. Can you confirm it works for you with QField 2.6+?

**Comment by DColby-UMS** [comment]
Nice work! Yes, it appears to be resolved. Thank you!




On Mar 7, 2023, at 4:06 PM, Ivan Ivanov ***@***.***> wrote:

﻿

@DColby-UMS<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_DColby-2DUMS&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=vBamEbb72uXBKpF5O4rEOQ&m=kdMke6lHIWpVH5lyCLHg8tsnGfeTQjdt1Tk9sFsNRAw&s=0Fb2mBlmJLVBd8xccW9MuP2-MerM8Sg-D0LH4ZkRCCI&e=> this should be fixed starting from last Sunday. Can you confirm it works for you with QField 2.6+?

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_opengisch_qfieldcloud_issues_472-23issuecomment-2D1458874328&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=vBamEbb72uXBKpF5O4rEOQ&m=kdMke6lHIWpVH5lyCLHg8tsnGfeTQjdt1Tk9sFsNRAw&s=u-IWkROxswxyGLIlLgNz-cpscjYRi6NTTyjxHOzVG5w&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_A5GN4WM3ND55BXKBNXWRR6DW26PM5ANCNFSM6AAAAAATYK4ONI&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=vBamEbb72uXBKpF5O4rEOQ&m=kdMke6lHIWpVH5lyCLHg8tsnGfeTQjdt1Tk9sFsNRAw&s=5tt-SFlO1EK_JrgLteF3NCkmRGCECaQF91VTVwqDtT4&e=>.
You are receiving this because you were mentioned.Message ID: ***@***.***>



________________________________

This email has been scanned for spam and viruses by Proofpoint Essentials. Click here<https://us3.proofpointessentials.com/index01.php?mod_id=11&mod_option=logitem&mail_id=1678223184-wPviSaxv64gz&r_address=dcolby%40umsi.us&report=1> to report this email as spam.
