### ISSUE TITLE
Qfield Cloud support a latest handling of Z and M values from Qfield 2.6+

### ISSUE THREAD

**Issue by DColby-UMS** [opengisch/qfieldcloud#495]
Just curious as to when this update is expected. We have reverted back to 2.5 for now as a work around.  Does anyone have an ETA on when this update will be applied to Qfield Cloud.  Thanks in advance!

**Comment by suricactus** [comment]
Duplicate of https://github.com/opengisch/qfieldcloud/issues/496 .
