### ISSUE TITLE
Login to self-hosted QFieldcloud with username

### ISSUE THREAD

**Issue by Forstrevier** [opengisch/qfieldcloud#521]
I have not been able to log in to my self-hosted QFieldCloud server from the Anroid tablet using the username on QField. However, with the email address (which can be used as an alternative to the username), the login worked.

When I use the username, I get an error message that the username or password is incorrect. After too many attempts I get "permission denied".
The same error occurs when I log in via QGIS and the extension. Again, it does not work with username, but with email address.

**Comment by sigsdis30** [comment]
Hi, 
I have the same problem. I wanted to know if something has been done on this subject ? 
Thanks

**Comment by suricactus** [comment]
I do not experience the same problem locally with the most recent QFC version (and before that tbh). Can you try to update your version? Mentioning the verions of your software is always helpful.
