### ISSUE TITLE
Delete Backup Files

### ISSUE THREAD

**Issue by TSanderPGG** [opengisch/qfieldcloud#526]
When I want to delete backup files to save storage, there is an option to also delete a number of versions older than the selected version. Unfortunately, the option shows the number of versions younger than the selected version:
![image](https://user-images.githubusercontent.com/80879779/220619265-a457ff61-f0bf-4493-a363-8e126b8a7035.png)
![image](https://user-images.githubusercontent.com/80879779/220619318-3e3f6819-292c-4bb8-b90e-e3937ffdfd2d.png)

It would be great if there could be an option inside QFieldCloud or maybe QFieldSync, where you can decide if backups of a file should be created.

**Comment by suricactus** [comment]
@TSanderPGG thanks for reporting this. We are already aware therer is a problem with the checkbox, fix will come in the next few days.

> It would be great if there could be an option inside QFieldCloud or maybe QFieldSync, where you can decide if backups of a file should be created.

Thanks for the proposal, will add it in our backlog for future development evaluation.

**Comment by TSanderPGG** [comment]
All right, thank you for your answer!

**Comment by suricactus** [comment]
Fixed in #528 , deployment in next days .
