### ISSUE TITLE
Delete File Versions: 500 Internal Server Error

### ISSUE THREAD

**Issue by miili** [opengisch/qfieldcloud#529]
Hi all,

delete a file and all its descendants results in a 500

![image](https://user-images.githubusercontent.com/4992805/220936744-ad61c0ea-fd4d-41e6-b365-b99188c0d775.png)

Around `2023-02-23T14:32:50.863230Z`

**Comment by suricactus** [comment]
@miili btw, is everythin ok after we merged your PR when the layer id was missing?

**Comment by miili** [comment]
Yes, that fixed the pipelines!
