### ISSUE TITLE
Organization more than 5 members are not accepted and returned a Server Error 500

### ISSUE THREAD

**Issue by hideoshiraishi** [opengisch/qfieldcloud#540]
### Issue: organization members more than 5 are not accepted
I am new to QFieldCloud. I registered myself as a new user and created one project.
The project needs more than 10 collaborators, thus I created an organization which is an owner of the project. The billing status is currently in a 'trial organisation'.

I invited several surveyors to QFieldCloud and they registered as new users.
They could be added to my organization up to five; however, when I tried to add a 6th member, it caused an error 'Server Error  (500)' as shown below.

![image](https://user-images.githubusercontent.com/41860959/222956500-c9e58e4d-71c3-4a5e-a578-8b69eb4425e4.png)

I deleted the 5th member and added another surveyor as a 5th member. It worked.
However, when I added the 6th member again, this error happened again.
I checked several web browsers in Windows 10, and tried to add different users as 6th member, but the situation does not change.

The organization plan says that "Minimum two users, pay only for additional active users". It seems to be the reason why I cannot add other "Community" membeers. Do they need to be "Pro" only for joining to a project as a collaborator or the organization owner should pay for the additional members? If the latter case, why I cannot add the members over 6?
Else, should my account be "pro"?

user name: hideoshiraishi
organization name: KanazawaUniversity
project name: QFieldTraining

The survey is going to start in a few days and it is fatal issue to start the survey properly.
Your advice is highly appreciated.

**Comment by suricactus** [comment]
@hideoshiraishi Thanks for your report, we will investigate your issue and report back soon.

**Comment by suricactus** [comment]
@hideoshiraishi hey, thanks for reporting. You `KanazawaUniversity` organization is currently using a trial organization. Trial organizations have limit of up to 5 organization members. Please upgrade to standard organization to be able to add more members in your organization.

The error 500 is something that is suboptiomal and we are working towards having more human readable message.
