### ISSUE TITLE
Mutualize ressources to avoid project specific synchronization

### ISSUE THREAD

**Issue by ponceta** [opengisch/qfieldcloud#559]
I tried a beta QFIELD project to store informations about trees and enhance management workflow using QFIELD and I face an interesting challenge :

![image](https://user-images.githubusercontent.com/8614223/224718427-5d68616d-db61-4d2e-a443-c94a0ab15ab2.png)

Most of my background data is taking 80-90% of the cloud size ressources in terms of upload and download.

This is not huge at this point but if I had like ten or twenty projects, this would be an issue in terms of trafic and used space.

These files are really appreciated for digitization purposes but if possible I would prefer to have these stored online at one single url.

Is there a way yet? 

When googling I find : https://github.com/opengeospatial/geoparquet

My idea would be to step on a similar concept as COG https://www.cogeo.org/ but for vector data used in QGIS/QFIELD

Would it be possible to refence a distant gpkg cloned locally for performance?

**Comment by m-kuhn** [comment]
This should be possible using vsicurl and geoparquet
