### ISSUE TITLE
Submodule for bootstrap not included correctly

### ISSUE THREAD

**Issue by stcz** [opengisch/qfieldcloud#577]
Currently, the bootstrap submodule is not correctly included:
```
$ git submodule 
-beb7de2dd69aa75f4b97e5a44e33deda09a34199 docker-qgis/libqfieldsync
```
It is missing as reference. In `.gitmodules` it is mentioned.

Further, the branch `v4.6.0` is not existing anymore in the branch.

**Comment by suricactus** [comment]
Hey, @stcz , thanks for digging in and finding this archeology sample. It needs to be removed, see #582 .
