### ISSUE TITLE
Documentation of local environment doesn't succeed

### ISSUE THREAD

**Issue by stcz** [opengisch/qfieldcloud#579]
I'd try to get qfieldcloud running locally, but I didn't manage to do this. 

I followed the instructions in the README.md. 

On my point of view, following the README.md and reading the .env file, there is no necessary change in .env, that should be required to run qfieldcloud locally. 
Changing secrets and personal information should be done anyway. I also tested different things here. 

What is unclear to me, what values `ENVIRONMENT` should/can have.

A bug i had looked at is #573. 

Further i recognized #577 but #578 should fix this if needed.

**Following the further instructions the services are running. When i open https://127.0.0.1:8011 i see the following:**
![image](https://user-images.githubusercontent.com/66465573/226173280-39dd3c81-737a-45bb-9f76-0422c9ab9405.png)
Is it intended, that the page is not found?

**Opening the login page, it looks very basic:**
![image](https://user-images.githubusercontent.com/66465573/226173354-bb8b350d-32e7-49ae-935e-3ae312850160.png)
Is this indented? Did i something wrong, or are there tempaltes missing, intended or unintended?

**Finally i created an account and logged in:**
![image](https://user-images.githubusercontent.com/66465573/226173487-120bd7a7-a594-4eeb-b239-f03c8e55febe.png)
But then i don't see any content anymore. 

I'm very confused about this and struggeling with my skills. 

Is it me, or are there Bugs? Is the Documentation incomplete? Is this indended or not?

Did anyone manage it to run qfieldcloud locally?

My environment is Ubuntu 22.04 running docker 23.0.1

Thanks for your help!

**Comment by stcz** [comment]
Thanks for your advice @suricactus.

I also managed it already to login into the django admin site. I created accounts, organizations etc. and it seems to work. But i'm wondering about the missing UI. Is this indented?

**Comment by suricactus** [comment]
With this repository you can do everything you can do with the qfield.cloud in terms of functionality - create projects, orgs, teams, sync from QFieldSync and QField, apply changes and more.

qfield.cloud is a service built on top of https://github.com/opengisch/qfieldcloud and it is a separate product.

**Comment by stcz** [comment]
That sounds reasonable. Thanks for your explanation.
