### ISSUE TITLE
Templates - What are artifacts of qfield.cloud and what is needed?

### ISSUE THREAD

**Issue by stcz** [opengisch/qfieldcloud#584]
Digging a bit more because of #579 I recognized the templates. 

E.g. `docker-app/qfieldcloud/core/templates/admin/base_site.html` contains:
```
{% extends "admin/base.html" %}
```
This file doesn't exist.
Is this maybe an artifact of qfield.cloud?

Same for other templates.

**Comment by suricactus** [comment]
No, all `admin` templates are built-in in Django and part of the Django Admin framework.
