### ISSUE TITLE
cleanup @deprecated

### ISSUE THREAD

**Issue by faebebin** [opengisch/qfieldcloud#626]
examples:

SubscriptionQuerySet.active ( b70d2704585f8f83a71fbed4cde22e403c9bb41dba7516233f4f63f37245bca2R336 )

AbstaractSubscriptoin.get_or_create_active_subscription 

https://github.com/opengisch/qfieldcloud/pull/620

https://github.com/opengisch/qfieldcloud/pull/625

both repose public

**Comment by suricactus** [comment]
These specfic examples of deprecated code have been removed.
