### ISSUE TITLE
Module Not Found Error - libqfieldsync.layer

### ISSUE THREAD

**Issue by lauro-ss** [opengisch/qfieldcloud#642]
Hi, I hope everyone is doing well.

I recently published qfieldcloud on azure virtual machine (ubuntu 20.04), made changes to the `.env` file and run the status command `docker compose exec app python manage.py status` and it returned that the states were all `redis: ok , geodb: ok, storage: ok`

I can log in in the QGIS desktop application, however, when performing the synchronization between QfieldCloud and QGIS returns the following error on the jobs section on QFieldCloud Admin:

Output pre:
  ```
Traceback (most recent call last):
    File "/usr/src/app/entrypoint.py", line 10, in <module>
      import qfieldcloud.qgis.process_projectfile
    File "/usr/src/app/lib/qfieldcloud/qgis/process_projectfile.py", line 6, in <module>
      from qfieldcloud.qgis.utils import BaseException, get_layers_data, layers_data_to_string
    File "/usr/src/app/lib/qfieldcloud/qgis/utils.py", line 19, in <module>
      from libqfieldsync.layer import LayerSource
  ModuleNotFoundError: No module named 'libqfieldsync.layer'
```

Feedback pre:
```
{
  "container_exit_code": 1,
  "error": "[Errno 2] No such file or directory: '/tmp/tmpm8gyjm1f/feedback.json'",
  "error_origin": "worker_wrapper",
  "error_stack": [
    "  File \"/usr/src/app/worker_wrapper/wrapper.py\", line 130, in run\n    with open(self.shared_tempdir.joinpath(\"feedback.json\"), \"r\") as f:\n"
  ]
}
```

The problem is followed by some mistake i made in the configuration process or this `libqfieldsync` should be installed after in another process? I Found this repository on github https://github.com/opengisch/libqfieldsync, for this problem resolves its necessary configure this?

**Comment by lauro-ss** [comment]
My mistake, sorry. 
it's was just execute this sequence commands:
`git submodule init`
`git submodule update`

It will download the submodule libqfieldsnyc.

**Comment by PierreSerpe** [comment]
Hello, I have also the following error: ModuleNotFoundError: No module named 'libqfieldsync.layer'

How did you tackle that problem?

**Comment by PierreSerpe** [comment]
after running the commands :
git submodule init
git submodule update
I get the following error:
QFSFileEngine::open: No file name specified
