### ISSUE TITLE
synchronisation problem due to inactive account

### ISSUE THREAD

**Issue by HoemmeGbR** [opengisch/qfieldcloud#661]
Hello,

I seem to not be able to synchronise my projects anymore.

I get the following error message:
"(Download-Fehler Packaging job finished unsuccessfully for 'ProjectName'. [QF/inactive_subscription] Permission denied because the subscription is inactive)"

My User account -> is active

My organisation however is inactive, we paid for the all year and I do not know how to change the status of my organisation to "active".

Has someone already had this problem? Can someone help me??

PS: I am really sorry, I am not sure where/how I should be writting about this problem so I am trying my luck here.

**Comment by suricactus** [comment]
Hey, @HoemmeGbR thanks for reporting this. There is a little "question mark" button down right on app.qfield.cloud, which contacts you to our support. Here is more for technical conversation. 

![image](https://github.com/opengisch/qfieldcloud/assets/2820439/016c2c87-556f-4959-96f7-7a241c9b32fb)

Can you please send your issue there or share you organization name here and we will check the payment status and reactivate your account>
