### ISSUE TITLE
QField Cloud - Process QGIS Project File - Can timeout be increased over 600 seconds?

### ISSUE THREAD

**Issue by KatieWM** [opengisch/qfieldcloud#724]
I am trying to update a QGIS Project in QField Cloud but when I add some additional layers it takes longer that 600 seconds for the job to process and it fails due to time out limit. The process times out at the 'Generate Thumbnail' step, no issues before that. Is there a way to increase the timeout limit? I do have a large number of layers in there but it performs well on the device and allows us to have one project for collecting many things. (Has 61 layers, about half tables).

![image](https://github.com/opengisch/qfieldcloud/assets/115957670/9065932f-0034-4133-a629-2b0f7a016cfe)

**Comment by m-kuhn** [comment]
Hello there 👋

Could tou let me know the username and project name on which this happened?
Thank you!
