### ISSUE TITLE
self hosted Cloud : Failed to upload "data.gpkg": [QT-2] Connexion fermée

### ISSUE THREAD

**Issue by sigsdis30** [opengisch/qfieldcloud#755]
Hi,
We have implemented your QFieldCloud on our server.
Our cloud runs on DEBIAN12 OS with a i5 processor, 16GB RAM and 500Go of disk space.
The configuration has been mounted under DOCKER as specified in the GitHub page and we run the docker-compose.override.test.yml.

I can't upload a qgs project or any gpkg because the Connexion is closed. 
The errors are "Failed to upload "data.gpkg": [QT-2] Connexion fermée" or "Aborted "communes.gpkg" upload". We have solved the subscription problem but I don't know what causes these problems. 

Can you help me ? 

Thank you

**Comment by sigsdis30** [comment]
Hi, 
Have you looked at this issue ? I really need help with it...
Thanks

**Comment by suricactus** [comment]
Feel free to ask for dedicated support at sales@opengis.ch .
