### ISSUE TITLE
Inactive organization with the 28 days trial organization

### ISSUE THREAD

**Issue by sigsdis30** [opengisch/qfieldcloud#763]
Hi, 
I'm trying to use the "28 days trial organization" but the current subscription has the status inactive. 

Also, I cannot create a project with this organization because I have the error : "500 Internal Server Error
We're sorry, but something went wrong on our end. Our team has been notified and we're working to fix it as soon as possible."

Can you help me please ? 
Thank you

**Comment by suricactus** [comment]
Hey! Did you contact [our support](https://support.qfield.cloud/portal/en/newticket?departmentId=116946000000442061)? The issue queue is more for speciifc code related issues rather than operations.
