### ISSUE TITLE
Installation without Docker ?

### ISSUE THREAD

**Issue by lapineige** [opengisch/qfieldcloud#765]
Hello,

I'm trying to figure out how to install your software without using Docker.

I can't find any installation instructions for this. Is there such a documentation somewhere ?
If not, could you point me to the files I could study to learn how to make such an installation ? (I'm not familiar with Docker).

Thank you very much

**Comment by lapineige** [comment]
I'm trying an :up: here in case this wasn't seen :)

Any help to install it without Docker would be greatly appreciated, as it's a blocking condition in my case.
For more context, I'm willing to package it for [Yunohost](yunohost.org/), which would allow many people to install it on their personal server in a quite easy way.

Thank you

**Comment by suricactus** [comment]
Hello @lapineige . QFieldCloud is not intended to be installed without Docker, therefore you cannot find any instructions how to install in without Docker. Please contact us at sales [at] opengis.ch if you really want to work together to find a speciic solution for your use case.
