### ISSUE TITLE
Minio installation error

### ISSUE THREAD

**Issue by floriansenf** [opengisch/qfieldcloud#803]
I've run the following command: docker compose up -d --build 

And I receive this error:
 ✔ Network qfieldcloud_default                          Created                                                                                               
 ✔ Volume "qfieldcloud_smtp4dev_data"                   Created                                                                                               
 ✔ Volume "qfieldcloud_minio_data3"                     Created                                                                                                
 ✔ Volume "qfieldcloud_minio_data4"                     Created                                                                                            
 ✔ Volume "qfieldcloud_transformation_grids"            Created                                                                                           
 ✔ Volume "qfieldcloud_media_volume"                    Created                                                                                               
 ✔ Volume "qfieldcloud_postgres_data"                   Created                                                                                               
 ✔ Volume "qfieldcloud_geodb_data"                      Created                                                                                               
 ✔ Volume "qfieldcloud_minio_data1"                     Created                                                                                               
 ✔ Volume "qfieldcloud_static_volume"                   Created                                                                                               
 ✔ Volume "qfieldcloud_certbot_www"                     Created                                                                                               
 ✔ Volume "qfieldcloud_minio_data2"                     Created                                                                                              
 ✔ Container qfieldcloud-worker_wrapper-1               Started                                                                                               
 ✔ Container qfieldcloud-qgis-1                         Started                                                                                             
 ✔ Container qfieldcloud-certbot-1                      Started                                                                                              
 ✔ Container qfieldcloud-mkcert-1                       Started                                                                                              
 ✔ Container qfieldcloud-geodb-1                        Started                                                                                               
 ✔ Container qfieldcloud-smtp4dev-1                     Started                                                                                               
 ✔ Container qfieldcloud-memcached-1                    Started                                                                                               
 ✔ Container qfieldcloud-mirror_transformation_grids-1  Started                                                                                               
 ✔ Container qfieldcloud-nginx-1                        Started                                                                                             
 ✘ Container qfieldcloud-minio-1                        Error                                                                                                 
 ✔ Container qfieldcloud-db-1                           Started                                                                                               
 ✔ Container qfieldcloud-app-1                          Started                                                                                           
 ✔ Container qfieldcloud-createbuckets-1                Created                                                                                             
 ✔ Container qfieldcloud-ofelia-1                       Started                     

I am not sure how this is connected to Minio but I found this in the logs:
qfieldcloud-mirror_transformation_grids-1  | --2023-10-10 19:32:56--  http://chmod/
qfieldcloud-mirror_transformation_grids-1  | Resolving chmod (chmod)... failed: Try again.
qfieldcloud-mirror_transformation_grids-1  | wget: unable to resolve host address 'chmod'
qfieldcloud-mirror_transformation_grids-1  | --2023-10-10 19:33:01--  http://a+r/
qfieldcloud-mirror_transformation_grids-1  | Resolving a+r (a+r)... failed: Try again.
qfieldcloud-mirror_transformation_grids-1  | wget: unable to resolve host address 'a+r'
qfieldcloud-mirror_transformation_grids-1  | /transformation_grids/*: Scheme missing.
qfieldcloud-mirror_transformation_grids-1  | FINISHED --2023-10-10 19:33:06--
qfieldcloud-mirror_transformation_grids-1  | Total wall clock time: 4m 37s
qfieldcloud-mirror_transformation_grids-1  | Downloaded: 418 files, 702M in 18s (40.0 MB/s)
qfieldcloud-mirror_transformation_grids-1  | --2023-10-10 19:49:24--  https://cdn.proj.org/
qfieldcloud-mirror_transformation_grids-1  | Resolving [cdn.proj.org](http://cdn.proj.org/) ([cdn.proj.org](http://cdn.proj.org/))... 99.86.4.20, 99.86.4.118, 99.86.4.86, ...
qfieldcloud-mirror_transformation_grids-1  | Connecting to [cdn.proj.org](http://cdn.proj.org/) ([cdn.proj.org](http://cdn.proj.org/))|99.86.4.20|:443... connected.
qfieldcloud-mirror_transformation_grids-1  | HTTP request sent, awaiting response... 304 Not Modified
qfieldcloud-mirror_transformation_grids-1  | File '/transformation_grids/index.html' not modified on server. Omitting download.
qfieldcloud-mirror_transformation_grids-1  | 
qfieldcloud-mirror_transformation_grids-1  | --2023-10-10 19:49:25--  http://chmod/
qfieldcloud-mirror_transformation_grids-1  | Resolving chmod (chmod)... failed: Try again.
qfieldcloud-mirror_transformation_grids-1  | wget: unable to resolve host address 'chmod'
qfieldcloud-mirror_transformation_grids-1  | --2023-10-10 19:49:30--  http://a+r/
qfieldcloud-mirror_transformation_grids-1  | Resolving a+r (a+r)... failed: Try again.
qfieldcloud-mirror_transformation_grids-1  | wget: unable to resolve host address 'a+r'
qfieldcloud-mirror_transformation_grids-1  | /transformation_grids/*: Scheme missing.

Any solutions how to solve this?

**Comment by suricactus** [comment]
Hey! There is most definitely problem with your local setup. `mirror_transformation_grids` service is not related to the `minio` in any sense. Check the logs shown by `docker compose logs minio` for more information. If you still cannot find the issue, feel free to paste them here.

**Comment by suricactus** [comment]
See #795

**Comment by floriansenf** [comment]
Interestingly, it shows me the same in minio logs.

What can I do about the mirror_transformation_grids issue?

I removed the project out of docker, reinstalled it, restarted server, cleaned everything else on my server but it's still this issue.
