### ISSUE TITLE
Self-hosted instance - qfieldcloud_default not found at the end of the project sync

### ISSUE THREAD

**Issue by mdouchin** [opengisch/qfieldcloud#804]
Hi all,

I am testing the docker-based local QFieldCloud stack. I managed to build it, run it, and configure it.

I can connect from the QFieldSync plugin in QGIS, and I can create a project and send it and its files.
But at the end of the first project creation (when the project is sent to the QfieldCloud instance), the status of the project is marked as Failed (red dot). 
I can see the green message in QGIS "Finished uploading the project to QFieldCloud"

I checked the minio server, and I can find the project and geopackage file in the Minio web console http://localhost:8010/browser/qfieldcloud-local/

When I go to QFieldCloud admin panel, http://localhost:7080/admin/core/job/21f2877d-b7bb-41ef-9db4-89767eb027c4/change/
I have this error :

```json
{
  "error": "404 Client Error: Not Found (\"network qfieldcloud_default not found\")",
  "error_origin": "worker_wrapper",
  "error_stack": [
    "  File \"/usr/src/app/worker_wrapper/wrapper.py\", line 123, in run\n    exit_code, output = self._run_docker(\n",
    "  File \"/usr/src/app/worker_wrapper/wrapper.py\", line 275, in _run_docker\n    container: Container = client.containers.run(  # type:ignore\n",
    "  File \"/usr/local/lib/python3.10/site-packages/docker/models/containers.py\", line 809, in run\n    container.start()\n",
    "  File \"/usr/local/lib/python3.10/site-packages/docker/models/containers.py\", line 400, in start\n    return self.client.api.start(self.id, **kwargs)\n",
    "  File \"/usr/local/lib/python3.10/site-packages/docker/utils/decorators.py\", line 19, in wrapped\n    return f(self, resource_id, *args, **kwargs)\n",
    "  File \"/usr/local/lib/python3.10/site-packages/docker/api/container.py\", line 1095, in start\n    self._raise_for_status(res)\n",
    "  File \"/usr/local/lib/python3.10/site-packages/docker/api/client.py\", line 263, in _raise_for_status\n    raise create_api_error_from_http_exception(e)\n",
    "  File \"/usr/local/lib/python3.10/site-packages/docker/errors.py\", line 31, in create_api_error_from_http_exception\n    raise cls(e, response=response, explanation=explanation)\n"
  ]
}
```

It seems the local network `qfieldcloud_default` has not been found. It is defined as this in my `docker-compose.yml` file
`QFIELDCLOUD_DEFAULT_NETWORK: qfieldcloud_default` 
but the other variable `QFIELDCLOUD_NETWORK=qfieldcloud`

Should I use `qfieldcloud` also for the `QFIELDCLOUD_DEFAULT_NETWORK` variable ?

Thanks in advance

**Comment by mdouchin** [comment]
I forgot to tell that the job status code is `failed_process_projectfile`, but I can see the files when refreshing in the job admin page

![image](https://github.com/opengisch/qfieldcloud/assets/3492210/3632d26c-306d-40f8-a3af-fcb0a5205ee4)

**Comment by mdouchin** [comment]
hum I may not have created the second docker network -> will test 
```
source .env && docker network create $QFIELDCLOUD_DEFAULT_NETWORK
```

**Comment by mdouchin** [comment]
I reverted my changes:

* delete the newly created network
* replaced `QFIELDCLOUD_DEFAULT_NETWORK: qfieldcloud_default` by `QFIELDCLOUD_DEFAULT_NETWORK: qfieldcloud` in the `docker-compose.yml`
* restarted the stack

No more network related errors, but a new one I will investigate ;)

**Comment by mdouchin** [comment]
I close this ticket as it has been solved.

**Comment by kachmul2004** [comment]
> I close this ticket as it has been solved.

Hi, could you please share the steps you took to resolve this problem?

**Comment by mdouchin** [comment]
Hi @kachmul2004 as posted above, I did the following

> replaced `QFIELDCLOUD_DEFAULT_NETWORK: qfieldcloud_default` by `QFIELDCLOUD_DEFAULT_NETWORK: qfieldcloud` in the docker-compose.yml
