### ISSUE TITLE
tasks always failling since last update

### ISSUE THREAD

**Issue by sslizz34422** [opengisch/qfieldcloud#816]
Hello, 

I'm struggling to make my struggling to build a server for since the last update, all the jobs are marked as flailed. 
the output pre
`
Traceback (most recent call last):
  File "/usr/src/app/entrypoint.py", line 10, in <module>
    import qfieldcloud.qgis.process_projectfile
  File "/usr/src/app/lib/qfieldcloud/qgis/process_projectfile.py", line 6, in <module>
    from qfieldcloud.qgis.utils import BaseException, get_layers_data, layers_data_to_string
  File "/usr/src/app/lib/qfieldcloud/qgis/utils.py", line 20, in <module>
    from libqfieldsync.layer import LayerSource
ModuleNotFoundError: No module named 'libqfieldsync.layer'
`
Feedback pre:

`
{
  "container_exit_code": 1,
  "error": "[Errno 2] No such file or directory: '/tmp/tmpjovwd0ps/feedback.json'",
  "error_origin": "worker_wrapper",
  "error_stack": [
    "  File \"/usr/src/app/worker_wrapper/wrapper.py\", line 187, in run\n    with open(self.shared_tempdir.joinpath(\"feedback.json\")) as f:\n"
  ]
}
`

I tried on new machine but not success. can Any one help .

**Comment by suricactus** [comment]
I am sure adding some reference versions that you have been using before and after can help a lot.

**Comment by sslizz34422** [comment]
thank you for your answer. I've been using V.0.22.2. now V.0.22.3 . I don't know what I'm doing wrong but I keep getting the same error every time I upload a project.

**Comment by suricactus** [comment]
What if you revert back to 0.22.2? Do you get all your problems fixed?

**Comment by sslizz34422** [comment]
yes I’ve made a clean installation with the previous version but no look .
Same error .

**Comment by suricactus** [comment]
Just reread you initial comment. Please checkout all submodules and try again. The problem was that you overlooked that in the README.md.
```
git pull --recurse-submodules  && git submodule update --recursive
```
