### ISSUE TITLE
Subscription inactive on free account Qfield Cloud

### ISSUE THREAD

**Issue by franciscocontreras93** [opengisch/qfieldcloud#825]
Hello! I am having an error "QF/inactive subscription/Permission denied because the subscription is inactive" when syncing a project on a free account. I have already reviewed the discussion https://github.com/opengisch/qfieldcloud/issues/668 but this is not the case since it is not self hosted. Greetings!!

**Comment by suricactus** [comment]
Hello! Can you please [contact our support](https://support.qfield.cloud/portal/en/newticket?departmentId=116946000000442061&layoutId=116946000000447348) and share your username to them. Thank you!

**Comment by georgiaslim** [comment]
I am having the same problem.
