### ISSUE TITLE
Create own server cloud instance and connect Qfield to it

### ISSUE THREAD

**Issue by PierreSerpe** [opengisch/qfieldcloud#832]
Hi All,

I m interested to create a Qfield Cloud on my synology NAS. I m running Ubuntu server on a virtual machine.
the 15 containers are running as you can see below.
I did create a new superuser and would like to connect to my own cloud with Qfield. 

Could you tell me what the adress and port should be? (https? or http? ip of the virtual machine? port?)
One more thing, I had to change the default geodb port from 5432 to 5434 due to the following error when building:  _5432 is used by postgres_ 

[+] Running 15/15
 ✔ Network qfieldcloud_default                          Created                                                                                                                          0.4s
 ✔ Container qfieldcloud-qgis-1                         Started                                                                                                                          0.8s
 ✔ Container qfieldcloud-db-1                           Started                                                                                                                          0.8s
 ✔ Container qfieldcloud-minio-1                        Healthy                                                                                                                          0.9s
 ✔ Container qfieldcloud-mirror_transformation_grids-1  Started                                                                                                                          0.9s
 ✔ Container qfieldcloud-smtp4dev-1                     Started                                                                                                                          0.8s
 ✔ Container qfieldcloud-certbot-1                      Started                                                                                                                          0.9s
 ✔ Container qfieldcloud-mkcert-1                       Started                                                                                                                          0.8s
 ✔ Container qfieldcloud-nginx-1                        Started                                                                                                                          0.9s
 ✔ Container qfieldcloud-worker_wrapper-1               Started                                                                                                                          0.9s
 ✔ Container qfieldcloud-geodb-1                        Started                                                                                                                          0.9s
 ✔ Container qfieldcloud-memcached-1                    Started                                                                                                                          0.8s
 ✔ Container qfieldcloud-app-1                          Started                                                                                                                          0.4s
 ✔ Container qfieldcloud-createbuckets-1                Started                                                                                                                          0.4s
 ✔ Container qfieldcloud-ofelia-1                       Started

**Comment by PierreSerpe** [comment]
I manage to connect to Qfield Cloud admin page after adding to the server IP in the .env on DJANGO_ALLOWED_HOST line
![image](https://github.com/opengisch/qfieldcloud/assets/102526566/65bcc089-824e-487a-9236-7e72182540fa)

**Comment by PierreSerpe** [comment]
In Qfield Cloud admin in menu Core\Jobs i get the following error :
Output pre:

Traceback (most recent call last):
  File "/usr/src/app/entrypoint.py", line 10, in <module>
    import qfieldcloud.qgis.process_projectfile
  File "/usr/src/app/lib/qfieldcloud/qgis/process_projectfile.py", line 5, in <module>
    from qfieldcloud.qgis.utils import (
  File "/usr/src/app/lib/qfieldcloud/qgis/utils.py", line 20, in <module>
    from libqfieldsync.layer import LayerSource
ModuleNotFoundError: No module named 'libqfieldsync.layer'

Feedback pre:

{
  "container_exit_code": 1,
  "error": "[Errno 2] No such file or directory: '/tmp/tmpjuokp5o_/feedback.json'",
  "error_origin": "worker_wrapper",
  "error_stack": [
    "  File \"/usr/src/app/worker_wrapper/wrapper.py\", line 188, in run\n    with open(self.shared_tempdir.joinpath(\"feedback.json\")) as f:\n"
  ]
}

**Comment by suricactus** [comment]
Hello. Thanks for using QFieldCloud. Seems you have misconfigured your QFieldCloud instance. Most probably, you did not configure properly the following env variable:
```
# QFieldCloud URL used within the worker as configuration for qfieldcloud-sdk
QFIELDCLOUD_WORKER_QFIELDCLOUD_URL=http://app:8000/api/v1/
```
Which is the endpoint the worker containers are connecting to. You should add the public IP/domain instead of app:8000.

If you need professional support to install QFieldCloud on your server, please contact us on sales@qfield.cloud.

**Comment by PierreSerpe** [comment]
@suricactus,

Sorry to re-open this one but i did not get an answer from sales@qfield.cloud
I have set the # QFieldCloud URL used within the worker as configuration for qfieldcloud-sdk
QFIELDCLOUD_WORKER_QFIELDCLOUD_URL=http://mypublicdomain/api/v1/

using qfieldcloud-cli for download i get the following:

pierreserpe@ubuntu-server:~$ qfieldcloud-cli -u pierreserpe -p _MYPASSWORD_ -U http://localhost:8011/api/v1/ download-files Liege /home/
Downloading project "Liege" files to /home/…
Requested "http://localhost:8011/api/v1/files/Liege/?skip_metadata=1" and got "404 Not Found":
b'<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta http-equiv="content-type" content="text/html; charset=utf-8">\n  <title>Page not found at /api/v1/files/Liege/</title>\n  <meta name="robots" content="NONE,NOARCHIVE">\n  <style type="text/css">\n    html * { padding:0; margin:0; }\n    body * { padding:10px 20px; }\n    body * * { padding:0; }\n    body { font:small sans-serif; background:#eee; color:#000; }\n    body>div { border-bottom:1px solid #ddd; }\n    h1 { font-weight:normal; margin-bottom:.4em; }\n    h1 span { font-size:60%; color:#666; font-weight:normal; }\n    table { border:none; border-collapse: collapse; width:100%; }\n    td, th { vertical-align:top; padding:2px 3px; }\n    th { width:12em; text-align:right; color:#666; padding-right:.5em; }\n    #info { background:#f6f6f6; }\n    #info ol { margin: 0.5em 4em; }\n    #info ol li { font-family: monospace; }\n    #summary { background: #ffc; }\n    #explanation { background:#eee; border-bottom: 0px none; }\n    pre.exception_value { font-family: sans-serif; color: #575757; font-size: 1.5em; margin: 10px 0 10px 0; }\n  </style>\n</head>\n<body>\n  <div id="summary">\n    <h1>Page not found <span>(404)</span></h1>\n    \n    <table class="meta">\n      <tr>\n        <th>Request Method:</th>\n        <td>GET</td>\n      </tr>\n      <tr>\n        <th>Request URL:</th>\n        <td>http://localhost:8011/api/v1/files/Liege/?skip_metadata=1</td>\n      </tr>\n      \n    </table>\n  </div>\n  <div id="info">\n    \n      <p>\n      Using the URLconf defined in <code>qfieldcloud.urls</code>,\n      Django tried these URL patterns, in this order:\n      </p>\n      <ol>\n        \n          <li>\n            \n                \n                [name=\'index\']\n            \n          </li>\n        \n          <li>\n            \n                swagger.yaml\n                [name=\'openapi_schema\']\n            \n          </li>\n        \n          <li>\n            \n                swagger/\n                [name=\'openapi_swaggerui\']\n            \n          </li>\n        \n          <li>\n            \n                docs/\n                [name=\'openapi_redoc\']\n            \n          </li>\n        \n          <li>\n            \n                admin/api/files/&lt;uuid:projectid&gt;/\n                \n            \n          </li>\n        \n          <li>\n            \n                admin/api/files/&lt;uuid:projectid&gt;/&lt;path:filename&gt;/\n                [name=\'project_file_download\']\n            \n          </li>\n        \n          <li>\n            \n                admin/\n                \n            \n          </li>\n        \n          <li>\n            \n                api/v1/auth/login/\n                \n            \n          </li>\n        \n          <li>\n            \n                api/v1/auth/token/\n                \n            \n          </li>\n        \n          <li>\n            \n                api/v1/auth/user/\n                \n            \n          </li>\n        \n          <li>\n            \n                api/v1/auth/logout/\n                \n            \n          </li>\n        \n          <li>\n            \n                api/v1/\n                \n            \n                projects/public/\n                \n            \n          </li>\n        \n          <li>\n            \n                api/v1/\n                \n            \n                \n                \n            \n                ^projects/$\n                [name=\'project-list\']\n            \n          </li>\n        \n          <li>\n            \n                api/v1/\n                \n            \n                \n                \n            \n                ^projects\\.(?P&lt;format&gt;[a-z0-9]+)/?$\n                [name=\'project-list\']\n            \n          </li>\n        \n          <li>\n            \n                api/v1/\n                \n            \n                \n                \n            \n                ^projects/(?P&lt;projectid&gt;[^/.]+)/$\n                [name=\'project-detail\']\n            \n          </li>\n        \n          <li>\n            \n                api/v1/\n                \n            \n                \n                \n            \n                ^projects/(?P&lt;projectid&gt;[^/.]+)\\.(?P&lt;format&gt;[a-z0-9]+)/?$\n                [name=\'project-detail\']\n            \n          </li>\n        \n          <li>\n            \n                api/v1/\n                \n            \n                \n                \n            \n                ^jobs/$\n                [name=\'jobs-list\']\n            \n          </li>\n        \n          <li>\n            \n                api/v1/\n                \n            \n                \n                \n            \n                ^jobs\\.(?P&lt;format&gt;[a-z0-9]+)/?$\n                [name=\'jobs-list\']\n            \n          </li>\n        \n          <li>\n            \n                api/v1/\n                \n            \n                \n                \n            \n                ^jobs/(?P&lt;job_id&gt;[^/.]+)/$\n                [name=\'jobs-detail\']\n            \n          </li>\n        \n          <li>\n            \n                api/v1/\n                \n            \n                \n                \n            \n                ^jobs/(?P&lt;job_id&gt;[^/.]+)\\.(?P&lt;format&gt;[a-z0-9]+)/?$\n                [name=\'jobs-detail\']\n            \n          </li>\n        \n          <li>\n            \n                api/v1/\n                \n            \n                \n                \n            \n                ^$\n                [name=\'api-root\']\n            \n          </li>\n        \n          <li>\n            \n                api/v1/\n                \n            \n                \n                \n            \n                ^\\.(?P&lt;format&gt;[a-z0-9]+)/?$\n                [name=\'api-root\']\n            \n          </li>\n        \n          <li>\n            \n                api/v1/\n                \n            \n                users/\n                \n            \n          </li>\n        \n          <li>\n            \n                api/v1/\n                \n            \n                users/&lt;str:username&gt;/organizations/\n                \n            \n          </li>\n        \n          <li>\n            \n                api/v1/\n                \n            \n                users/&lt;str:username&gt;/\n                \n            \n          </li>\n        \n          <li>\n            \n                api/v1/\n                \n            \n                collaborators/&lt;uuid:projectid&gt;/\n                \n            \n          </li>\n        \n          <li>\n            \n                api/v1/\n                \n            \n                collaborators/&lt;uuid:projectid&gt;/&lt;str:username&gt;/\n                \n            \n          </li>\n        \n          <li>\n            \n                api/v1/\n                \n            \n                files/&lt;uuid:projectid&gt;/\n                \n            \n          </li>\n        \n          <li>\n            \n                api/v1/\n                \n            \n                files/&lt;uuid:projectid&gt;/&lt;path:filename&gt;/\n                [name=\'project_file_download\']\n            \n          </li>\n        \n          <li>\n            \n                api/v1/\n                \n            \n                files/meta/&lt;uuid:projectid&gt;/&lt;path:filename&gt;\n                [name=\'project_metafiles\']\n            \n          </li>\n        \n          <li>\n            \n                api/v1/\n                \n            \n                files/public/&lt;path:filename&gt;\n                [name=\'public_files\']\n            \n          </li>\n        \n          <li>\n            \n                api/v1/\n                \n            \n                packages/&lt;uuid:project_id&gt;/latest/\n                \n            \n          </li>\n        \n          <li>\n            \n                api/v1/\n                \n            \n                packages/&lt;uuid:project_id&gt;/latest/files/&lt;path:filename&gt;/\n                \n            \n          </li>\n        \n          <li>\n            \n                api/v1/\n                \n            \n                packages/&lt;uuid:project_id&gt;/&lt;uuid:job_id&gt;/files/&lt;path:filename&gt;/\n                \n            \n          </li>\n        \n          <li>\n            \n                api/v1/\n                \n            \n                qfield-files/&lt;uuid:projectid&gt;/\n                \n            \n          </li>\n        \n          <li>\n            \n                api/v1/\n                \n            \n                qfield-files/&lt;uuid:projectid&gt;/&lt;path:filename&gt;/\n                \n            \n          </li>\n        \n          <li>\n            \n                api/v1/\n                \n            \n                qfield-files/export/&lt;uuid:projectid&gt;/\n                \n            \n          </li>\n        \n          <li>\n            \n                api/v1/\n                \n            \n                members/&lt;str:organization&gt;/\n                \n            \n          </li>\n        \n          <li>\n            \n                api/v1/\n                \n            \n                members/&lt;str:organization&gt;/&lt;str:username&gt;/\n                \n            \n          </li>\n        \n          <li>\n            \n                api/v1/\n                \n            \n                status/\n                \n            \n          </li>\n        \n          <li>\n            \n                api/v1/\n                \n            \n                deltas/&lt;uuid:projectid&gt;/\n                \n            \n          </li>\n        \n          <li>\n            \n                api/v1/\n                \n            \n                deltas/&lt;uuid:projectid&gt;/&lt;uuid:deltafileid&gt;/\n                \n            \n          </li>\n        \n          <li>\n            \n                api/v1/\n                \n            \n                deltas/apply/&lt;uuid:projectid&gt;/\n                \n            \n          </li>\n        \n          <li>\n            \n                auth/\n                \n            \n          </li>\n        \n          <li>\n            \n                accounts/\n                \n            \n          </li>\n        \n          <li>\n            \n                ^invitations/\n                \n            \n          </li>\n        \n          <li>\n            \n                __debug__/\n                \n            \n          </li>\n        \n      </ol>\n      <p>\n        \n          The current path, <code>api/v1/files/Liege/</code>,\n        \n        didn\xe2\x80\x99t match any of these.\n      </p>\n    \n  </div>\n\n  <div id="explanation">\n    <p>\n      You\xe2\x80\x99re seeing this error because you have <code>DEBUG = True</code> in\n      your Django settings file. Change that to <code>False</code>, and Django\n      will display a standard 404 page.\n    </p>\n  </div>\n</body>\n</html>\n'
pierreserpe@ubuntu-server:~$ qfieldcloud-cli -u pierreserpe -p Orbe@rallonx30 -U http://localhost:8011/api/v1/ download-files Liege /home/
