### ISSUE TITLE
Serious issue with permissions management

### ISSUE THREAD

**Issue by timlinux** [opengisch/qfieldcloud#833]
When I change the permissions of one user, the permissions are applied to a different user. If you are not watching carefully, you can suddenly find that you have unintentionally created admin users.

In this example, I am trying to assign admin to 'luna_123' and instead 'mulamajeff' receives the admin rights.

[Screencast from 2023-12-11 08-04-11.webm](https://github.com/opengisch/qfieldcloud/assets/178003/a17bb4da-820f-4a74-89d9-b8de81e447d3)

Another example of unexpected behaviour:

[Screencast from 2023-12-11 07-59-14.webm](https://github.com/opengisch/qfieldcloud/assets/178003/ffb97fad-ca37-4ffc-8572-937c32ee29ae)

**Comment by SeqLaz** [comment]
Hello Tim,

Thank you for bringing this to our attention.

We sincerely appreciate your diligence in reporting the observed behavior. Our team is committed to investigating and resolving this issue.

Will keep you updated on the progress.

If you have any additional details or concerns, please feel free to share them or contact to us.

Best regards.

**Comment by woutegging** [comment]
Hi, 

I'm having the same issue. Can you give us an update on the progress of this issue? 

Best regards, 

Wout Egging

**Comment by suricactus** [comment]
Internal testing, fix will be deployed with the next update.
