### ISSUE TITLE
Get all features from cloud for initial import via API

### ISSUE THREAD

**Issue by JimPanse2k19** [opengisch/qfieldcloud#834]
While its possible to fetch the used files from the cloud using the API, it seems that only deltas ressource showing up a unified representation of points (x,y) ... is it also possible to get all of these points via the api? So when somebody creates a layer with 100 points and makes a qfield package from it and load it to the cloud, i want to "see" these points from another api using application without parsing the file format (gpk, xml etc.) behind it. is there any chance to see a initial "delta" for all points?

Any other idea?

**Comment by suricactus** [comment]
QFieldCloud does not provide WFS-like features. You need to directly connect to the datasource that stores your features.
