### ISSUE TITLE
some doubts creating own server cloud instance

### ISSUE THREAD

**Issue by snuffer82** [opengisch/qfieldcloud#835]
Hello,
I launched a server instance and the system correctly manages the data between QGIS and QField (this is great!!!). 
There are some things I don't understand:
1. my COMPOSE_FILE is still the default (COMPOSE_FILE=docker-compose.yml:docker-compose.override.local.yml). 
I don't understand what changes I need to make to go into production...
2. the /var/local/qfieldcloud folder does not contain any files
3. if I open the page relating to a PERSON and click on "View on site" I see this error
![error](https://github.com/opengisch/qfieldcloud/assets/17122286/9108b64f-ad07-4ab4-bbf7-ace5ff94a309)
Similar errors appear on the website when I perform some actions.

Can you give me some suggestions? Thank you
Paolo

**Comment by suricactus** [comment]
Thank you for running QFieldCloud. 

I cannot provide detailed answers on what you are dealing with, but I can try my best to guess.

1. You are running a local development version of QFieldCloud. If you want to use the production version, you should use `COMPOSE_FILE=docker-compose.yml:docker-compose.override.yml`. Note it is required to provide external Object Storage (s3) and PostGIS database services, they are not part of QFC stack.
2. not clear what you mean. Where is `/var/local/qfieldcloud ` located?
3. Confirmed error, added in the backlog to be fixed. See https://github.com/opengisch/qfieldcloud/issues/842

I am closing this issue as it is more a support request. If you need professional support, please contact us on sales@qfield.cloud.
