### ISSUE TITLE
Quote Variables in .env

### ISSUE THREAD

**Issue by stcz** [opengisch/qfieldcloud#843]
Declared Variables should be quoted in `.env.example` as it is best practice. 

# Problem:

E.g.:
```
GEODB_PASSWORD=KUAa7h!G&wQEmkS3
```
(see [here](https://github.com/opengisch/qfieldcloud/blob/34fda03ad74cdcbb89d53f90b7248d27e70d301d/.env.example#L59))

When the string is interpreted as in `./scripts/init_letsencrypt.sh` the `&` will terminate the command and lead to fail.

It would be better to quote all variables with `'`.

**Comment by suricactus** [comment]
Fixed in https://github.com/opengisch/qfieldcloud/pull/846 .
