### ISSUE TITLE
ID Hyperlink in QFieldCloud Changes tab no longer working

### ISSUE THREAD

**Issue by dmeis1** [opengisch/qfieldcloud#849]
When clicking on the ID hyperlink, I used to get a link to an overview map showing location and details of the feature. This link is no longer working. This link doesn't work for any feature regardless of "Status". I have attempted using Chrome and Microsoft Edge. Both have the same issue. 

![QFieldCloudIssue](https://github.com/opengisch/qfieldcloud/assets/155763430/aad30d72-92c2-4bdd-b37a-be7675ff630c)

**Comment by suricactus** [comment]
Thanks for reporting. We are aware, this will be fixed in the next release.

**Comment by suricactus** [comment]
This should be long fixed. Thanks for the report!
