### ISSUE TITLE
Qfield Cloud sync from Geopackage to PostGIS DB

### ISSUE THREAD

**Issue by geogeek11** [opengisch/qfieldcloud#856]
I have a Qfield cloud on a local server, I need to sync the Geopackage DB with a local postgis DB.
I have tested creating a qgis  project using a pgsql service but it did not work as expected as the changes do not get sync to the postgresql DB.

**Comment by suricactus** [comment]
Hello @geogeek11 . Can you please provide some further details what steps did you follow, how did you configure your project (if you share it even better), do you see any errors?

**Comment by geogeek11** [comment]
I have created an empty project using qfieldsync, then saved a new qgis project containing a postgis layer (using local credentials or using pgsql service) in the qfield cloud new empty project directory. 

I have found no way to add secrets in the qfieldCloud CE

I have already activated save to external db in subscription configuration.

**Comment by suricactus** [comment]
You can see the conversation about secrets in https://github.com/opengisch/qfieldcloud/issues/501 . Closing this issue as a duplicate.
