### ISSUE TITLE
PostGIS sync on QFieldCloud on-premise instance: Permission denied, plan is insufficient

### ISSUE THREAD

**Issue by mahmoodi-source** [opengisch/qfieldcloud#870]
Hey guys, I have a problem uploading project files to an existing empty project created on our QfieldCloud server. When I paste the project files in the local directory, everything is good, and the message says that "the entered path contains one QGIS project file. Exactly as it should be."

Now, when I sync the project through Qfield Sync, at the end, it will give me the error of failing to upload multiple projects.

and when I create a project through Qfield sync plugins in our QfieldCloud server and then upload the uploaded files in the directory, it uploads without problem, but it cannot be downloaded in the Qfield app and gives me the following error:
![image](https://github.com/opengisch/qfieldcloud/assets/144428014/dbdbe35e-e76e-4982-8338-92de4d1b587d)

I don't know what the problem is.
Can someone please walk me through the process? i would really appreciated.

**Comment by suricactus** [comment]
Please configure your subscriptions to allow postgis connection. It is is controlled via `Plan`is_external_db_supported`. Look at the other plan settings, you might find them useful or leading to other user messages.

**Comment by mahmoodi-source** [comment]
> Please configure your subscriptions to allow postgis connection. It is is controlled via `Plan`is_external_db_supported`. Look at the other plan settings, you might find them useful or leading to other user messages.

I didn't quite get you. What do you mean by "configuring your subscriptions to allow PostGIS connections?

**Comment by suricactus** [comment]
Are you sure the plan of the user/org who owns the project have it checked? If so, then it might be another misconfiguration in the plans.

**Comment by mahmoodi-source** [comment]
> Are you sure the plan of the user/org who owns the project have it checked? If so, then it might be another misconfiguration in the plans.

Positive.
Now I can upload the project to the Qdfield Cloud server, and the connection between the PostGIS_db and the Qdfield Cloud server is built. But when I followed the project on Qdield to edit the layers, they were unavaliable. and this is the error: 
![image](https://github.com/opengisch/qfieldcloud/assets/144428014/13200de0-bb5f-4dd9-bdc6-9aff0658b11c)
