### ISSUE TITLE
Creating geodbs fails on hosted database systems such as AWS RDS

### ISSUE THREAD

**Issue by Rikuoja** [opengisch/qfieldcloud#88]
Thanks everybody for releasing QField Cloud to the public! The documentation was excellent and I got an instance up and running in no time with your instructions :)

However, long story short: I am running into difficulties with the architecture when running on AWS. The reason is that I thought of using an AWS hosted PostgreSQL RDS, and it seems that in those cases, the so-called AWS "superuser" actually has no rights to create databases for other users unless they share a role: http://asheiduk.de/post/setup-pg-on-rds/

This results in Django returning
```
InsufficientPrivilege at /admin/core/geodb/add/
must be member of role "test_user"
```
when trying to create a new geodb with a new user in Django admin.

I know this is a limitation of AWS databases, and not really QField Cloud's fault.

So I was wondering, will I need to set up a custom database cluster if I want to test out QFieldCloud?

**Comment by Rikuoja** [comment]
Also, I would be interested in fixing this in a PR, if you think that this is an issue that should be addressed in QFieldCloud?

**Comment by suricactus** [comment]
Closed due to inactivity.
