### ISSUE TITLE
Layers from local folder in QFieldCloud project

### ISSUE THREAD

**Issue by DanasKaz** [opengisch/qfieldcloud#901]
Hi,

is it possible to add static layers (which do not need to be edited) from the local folder to the QFieldCloud project? Some layers are "heavy" (in terms of MB/GB), but they are static, so there is no point adding them to the QFieldCloud project, because they will never have any changes therefore they do not need any sync, but it is useful to have them as a background layer for example.
Thanks.

**Comment by SeqLaz** [comment]
Hi @DanasKaz, yes is completely possible by using the functionality of shared local dataset

https://docs.qfield.org/how-to/outside-layers/
