### ISSUE TITLE
Organization username field populated with current logged in user's username.

### ISSUE THREAD

**Issue by vboulianne** [opengisch/qfieldcloud#916]
When modifying organization, field "username" gets filled with logged in username.

![Capture (2024-03-22 10h33 29 sec)](https://github.com/opengisch/qfieldcloud/assets/80436985/ebb8658b-614e-4ad6-ba48-3a7eeb60e0c4)

**Comment by suricactus** [comment]
Thanks for reporting @vboulianne , but I cannot reproduce. Here I am running latest master.

![image](https://github.com/opengisch/qfieldcloud/assets/2820439/ed77d3d5-77c9-4266-95c0-7048186c7604)

**Comment by vboulianne** [comment]
I was running Master as well, but the cause is other. QFC was shown in a fringe browser, Falkon (QtWebEngine/Webkit?) under Ubuntu in VirtualBox. I just realized the replacement was related to the browser autofill. Disabling it solved the issue. Apologies.
