### ISSUE TITLE
How to connect to Qfiled from local QFiledCloud?

### ISSUE THREAD

**Issue by jshirokov-bs** [opengisch/qfieldcloud#923]
Hello!

I deployed QFieldCloud on my computer using the Readme file from the repository, using Ubuntu. I have successfully launched Docker, Minio opens on localhost.
However, when I launch the QGis plugin to connect to the cloud, I don't fully understand which username/password I need to use. Are they listed in the .env file? Or is it something else?

Is there a Swagger in the containers so that I can send requests for testing?

BR!

**Comment by suricactus** [comment]
Find your answer in the documentation attached: https://docs.qfield.org/get-started/tutorials/get-started-qfc/?h=double#change-the-default-qfieldcloud-server-in-qfield-and-qfield-sync
