### ISSUE TITLE
Two questions about QField features/functionality - automatisation and sync with DB

### ISSUE THREAD

**Issue by DanasKaz** [opengisch/qfieldcloud#928]
Hi,

could you help me with these questions:

a) is it possible to send changes you made in the QField to the QFieldCloud automatically? Button "Push changes" requires action from the user - is it possible to create a scheduler or install some plugin which would push changes automatically on preset time, say once per day?
b) If we use PostgreSQL DB for storing layers in QFieldCloud, how to push changes from the DB to the project on mobile device? Option "Synchronize" upload the whole layer/project - we just need to get small updates made in the DB.

Thanks.

**Comment by DanasKaz** [comment]
Regarding automatic push of changes - is it?

https://docs.qfield.org/get-started/tutorials/get-started-qfc/#enabling-automatic-pushing-of-changes-to-qfieldcloud

**Comment by suricactus** [comment]
Hey @DanasKaz .

As for a), you correctly found the relevant piece of documentation.

As for b), this is not supported yet.

We have b) in the backlog of issues with no immediate plans for development. If you are interested in speeding up such development, please drop us an email at sales [at] qfield.cloud.

**Comment by DanasKaz** [comment]
Hi,

thanks for reply.
Regarding b) - so the only way to get the changes made in DB on QField is to sync the whole project/layer, isn't it?
Thanks.

**Comment by suricactus** [comment]
You can always make a direct connection from QField to your PG layers, but you lose the offline editing. Other than that, QField always gets a full offline copy of your PG layers.
