### ISSUE TITLE
Project collaborators roles has no impact on admin site

### ISSUE THREAD

**Issue by geogeek11** [opengisch/qfieldcloud#935]
Qfield cloud new user has access to nothing in the admin site even after assigning a role to a user, the checkbox Staff Status allows to have an empty interface.

![image](https://github.com/opengisch/qfieldcloud/assets/7670475/5f71b91b-3623-4536-bd23-9657faa59ebc)

The project roles as described in this [link](https://docs.qfield.org/reference/qfieldcloud/permissions/) are only applied in Qfieldsync plugin level.

I have managed to create a new users group to display projects and people menus in the admin site, but I have to keep the Django group roles and Project roles in sync manually. 

Qfield Cloud : v 0.26.3
docker setup

**Comment by suricactus** [comment]
The roles that you have cited and the roles that are in Django admin are two separate things. Please read https://docs.djangoproject.com/en/5.0/topics/auth/default/ .
