### ISSUE TITLE
invalid_dataprovider on raster layers

### ISSUE THREAD

**Issue by CynthiaBorotPNV** [opengisch/qfieldcloud#952]
Hi,

When I add or synchronise my QField project on the cloud i get this error, only on my mbtiles rasters (It's display on the cloud web interface, on the mobile phone when i open a cloud project) : 
![image](https://github.com/opengisch/qfieldcloud/assets/31919455/84ac2a4e-a224-4c52-9f52-84895ec87fa4)

My raster layers are within the QFieldCloud directory  (in my example _FloreSentinelleQFieldCloud_):
![image](https://github.com/opengisch/qfieldcloud/assets/31919455/9c04f7dd-5a7c-4258-b268-79f4bd9c2a89)
![image](https://github.com/opengisch/qfieldcloud/assets/31919455/3a349b4c-7b50-479b-bc7e-1176dec569cd)

When I set the source of each layer to QFieldCloud directory (in my example _FloreSentinelleQFieldCloud_) , after each syncchronisation this configuration go back to QField directory (in my example _FloreSentinelleQField_) ... is it the error source ?
![image](https://github.com/opengisch/qfieldcloud/assets/31919455/3cd96787-c68c-4fff-b9a5-d0d5b3a5d311)

**Comment by Churros396** [comment]
I have the same issue on QGIS 3.34 using a tif file of 3GB. The online storage was upgraded to be sufficient.

**Comment by suricactus** [comment]
Hey @CynthiaBorotPNV, thanks for reporting. I have checked your project and also the logs of the jobs you have triggered. What I see is that the paths of the `.tif` files in your project are not correct. Let's look at the logs of your "Package job" with ID `c69da96d-c2ad-4937-9422-bd5c91cb17d6`:

```
11:11:33.138 QGSMSGLOG WARNING  15 unavailable layer(s) found:
11:11:33.138 QGSMSGLOG WARNING   * ../FloreSentinelleQField/ortho_bsm_plan-dechaud.mbtiles
11:11:33.138 QGSMSGLOG WARNING   * ../FloreSentinelleQField/ortho_pralo_bois-frumier.mbtiles
11:11:33.138 QGSMSGLOG WARNING   * ../FloreSentinelleQField/ortho_pralo_bois-tuilette.mbtiles
11:11:33.138 QGSMSGLOG WARNING   * ../FloreSentinelleQField/ortho_pralo_couloir-gd-pierre.mbtiles
11:11:33.138 QGSMSGLOG WARNING   * ../FloreSentinelleQField/ortho_pralo_foret-isertan.mbtiles
11:11:33.138 QGSMSGLOG WARNING   * ../FloreSentinelleQField/ortho_pralo_foret-noire.mbtiles
11:11:33.139 QGSMSGLOG WARNING   * ../FloreSentinelleQField/ortho_pralo_plan-leschaux.mbtiles
11:11:33.139 QGSMSGLOG WARNING   * ../FloreSentinelleQField/ortho_pralo_rn-tueda.mbtiles
11:11:33.139 QGSMSGLOG WARNING   * ../FloreSentinelleQField/ortho_termignon_coetet.mbtiles
11:11:33.139 QGSMSGLOG WARNING   * ../FloreSentinelleQField/ortho_termignon_roche-queua.mbtiles
11:11:33.139 QGSMSGLOG WARNING   * ../FloreSentinelleQField/ortho_termignon_sous-pierre-brune.mbtiles
11:11:33.139 QGSMSGLOG WARNING   * ../FloreSentinelleQField/ortho_termignon_st-marguerite.mbtiles
11:11:33.139 QGSMSGLOG WARNING   * ../FloreSentinelleQField/ortho_termignon_vers-sallanches.mbtiles
11:11:33.139 QGSMSGLOG WARNING   * ../FloreSentinelleQField/ortho_tignes-bois-de-la-laye.mbtiles
11:11:33.139 QGSMSGLOG WARNING   * ../FloreSentinelleQField/ortho_val-isere_pont-st-charles.mbtiles
```

Note there are two dots `..` in front of the files that are problematic. Two dots means "upper directory". So I assume in your file system you have your project organized as follows:

```
flore_sentinelle/ortho_bsm_plan-dechaud.mbtiles
flore_sentinelle/FloreSentinelleQFieldCloud/ortho_bsm_plan-dechaud.mbtiles
flore_sentinelle/FloreSentinelleQFieldCloud/FloreSentinelle2024_qfield_cloud.qgs
```
So when you open `flore_sentinelle/FloreSentinelleQFieldCloud/FloreSentinelle2024_qfield_cloud.qgs` files in QGIS, the actual files that is opened is `flore_sentinelle/ortho_bsm_plan-dechaud.mbtiles`, not `flore_sentinelle/FloreSentinelleQFieldCloud/ortho_bsm_plan-dechaud.mbtiles` as you would expect. You can prove this theory by simply moving the whole `flore_sentinelle/FloreSentinelleQFieldCloud` directory to a new location, e.g. a new directory created on your desktop. When you open your the `.qgs` project, you should see the same errors as on QFieldCloud.

To fix this, simply update the datasources of the problematic layers to use the paths in the current project directory, not in the parent one.

You can access the same logs if you open the web interface and navigate to your Projects -> Jobs and click on the Job with id "c69da96d".

**Comment by suricactus** [comment]
@CynthiaBorotPNV @Churros396 please use the dedicated QFieldCloud support when you experience issues like this for faster response time, this support forum is more technical and not the official support channel. You can access the ticketing platform from the question mark on app.qfield.cloud in bottom right or at support.qfield.cloud.
