### ISSUE TITLE
Deleting project collaboraters deletes the project?!?

### ISSUE THREAD

**Issue by 9ls1** [opengisch/QFieldCloud#959]
We have our own (self-hosted) QFieldCloud (ver. 0.26.4) installed on a server. Everything is working more or less very nicely.

However, today I wanted to remove project collaborators from a project from the QFieldCloud admin webpage (https://\<server url>/admin/core/project).
I checked the box to the right of the collaborator and clicked Delete.
I was in a hurry, so I didn't read the information carefully and just clicked  "Yes, I'm sure" (I knew which collaborators I wanted to remove and I had checked the correct boxes).
Too late I detected that I deleted the **whole project** from the cloud! 
I only wanted to delete three collaborator (out of four). 
And that's what I expected within the "Project collaborators"-tab (just an example from another project with only one collaborator). Here I would check the check box to the right:
![image](https://github.com/opengisch/qfieldcloud/assets/10632163/7bb1aa43-dca6-489a-a660-1e574e970eef)

When I want to delete the whole project, I have done it from the Projects list:
![image](https://github.com/opengisch/qfieldcloud/assets/10632163/f7af6a45-dbb4-472b-8f90-6760674a55cc)

I know I can blame myself for not reading carefully enough, but I would suggest that it should be possible to only delete (remove) collaborators within the "Project collaborators"-tab. (Luckily, we have back-up routines of the self-hosted cloud, so I could retrieve the deleted project.)

P.t. how do I delete (only) collaborators from a project in QFieldCloud admin?

**Comment by 9ls1** [comment]
I've figured it out:
Check the check box(es) to the right for the collaborators you want to delete (remove) and click Save.
![image](https://github.com/user-attachments/assets/5eef39ca-c396-4995-984b-da715c5cb5f2)

Reopen the project and the Project collaborators-tab, and you'll see the collaborator(s) are gone.
![image](https://github.com/user-attachments/assets/7485b89d-f44a-48f6-b2a1-f43033266427)

**Comment by suricactus** [comment]
This is a Django admin default functionality, we cannot do much here. Closing.
