### ISSUE TITLE
"Invalid subscription" error in QField

### ISSUE THREAD

**Issue by georgiaslim** [opengisch/qfieldcloud#960]
I am managing QField projects for an ecosystem restoration team. We are using QField to collect data, record progress, and help plan for future work-days. We have an organization account called "ReForest", (1.0 GB) set up with collaborators (all of whom are QFieldCloud Commuity Accounts) assigned to projects as Admins. Everything was working great for a week or two.

Now, after no changes to anything we do (except a QField update), we are all getting the same errors when we try to Synchronize projects on QField:
![QField Synchronize error](https://github.com/opengisch/qfieldcloud/assets/158478253/461f20a5-e97c-4864-b6a6-77c55b216a2f)

And in the message log:
![QField Invalid Subscription error](https://github.com/opengisch/qfieldcloud/assets/158478253/4ba848d8-0c2f-4161-ae92-fc0bcc1e5a20)

We are able to Push the changes to the cloud, though, so we've done this and I attempted to apply the changes in my web-browser from the QFieldCloud website itself, and this doesn't work either. I get these messages:

![Nyuki says](https://github.com/opengisch/qfieldcloud/assets/158478253/142dda61-5699-46e5-84f9-f98e05c2dbf7)

and

![QFieldCloud Pending error](https://github.com/opengisch/qfieldcloud/assets/158478253/bfa2f980-b099-4e3e-bf3b-7f30abeffb32)

I am stumped as to why the subscription is invalid; we are only using 12% of our total storage, we are not using remote sensors or remote layers (as far as I know, unless Google Basemaps are remote layers?), and there doesn't seem to be any information as to what specific features we are using that are not supported by our subscription, only suggestions. Does this have anything to do with the latest QField update? Or am I checking a checkbox somewhere by accident or some other user error? How can I fix this?

THANK YOU!

**Comment by suricactus** [comment]
Hello, @georgiaslim . Thanks for the detailed report. Note GitHub is for really technical communication regarding QFieldCloud. The operations of the service at app.qfield.cloud is handled at the following address: support.qfield.cloud .

Anyway, I had a look at your issue. You have been using a trial plan for the period May 13, 2024, 9:30 p.m.	to June 10, 2024, 9:30 p.m. and after that it expired, therefore you see the error message. Please upgrade or if you need further assistance, file a new ticket on the abovementioned platform.

**Comment by georgiaslim** [comment]
Ivan,

Thank you for your response. I appreciate you taking the time to address my
issue. We paid for the full version, but are still getting the error code;
we think maybe the payment is still processing.

As for the Support page, thank you for that resource, but it is not
allowing me to log-in with either email or QFieldCloud username and says
"no such user". I filed a ticket through the chat feature on qfield.cloud,
but have yet to receive a response.

I apologize for continuing to email you, but I am encountering a lot of new
issues here and there isn't any other means of support that I can find.


*Cullen "Slim" Brown*
Feed the People Farms <http://ftpfarms.wordpress.com>
I Want Whisky <https://iwantwhisky.bandcamp.com/>
Atlanta IWW GMB <https://www.iww.org/branches/US/GA>

***@***.*** ***@***.***>*

**Comment by suricactus** [comment]
@georgiaslim let's move the conversation on the ticketing platform. I see the above mentioned organization is active since 
June 14, 2024, 3:50 p.m. UTC, if you have any further questions on the service behind app.qfield.cloud, please don't hesitate to contact us on the ticketing platform.
