### ISSUE TITLE
Error with visualization of styles

### ISSUE THREAD

**Issue by jaromaco** [opengisch/qfieldcloud#988]
Hello everyone,

I try to deploy a QFieldCloud in a Linux Cloud Server, distro Ubuntu. When I enter by localhost in Windows, without problem. But when I enter in my hosted application, CSS and JQuery are not loaded. I attach the screenshots.

Regards.

![image](https://github.com/user-attachments/assets/ba837596-a378-40b1-9629-53ef3af28a1c)
![image](https://github.com/user-attachments/assets/125b6d56-f746-442c-beaf-6e2980186c9c)

**Comment by suricactus** [comment]
Hello @jaromaco , please make sure you run `collectstatic`. If the problem persists, please try to drop the `staticfiles` volume and rebuild the whole stack, then run `collectstatic`.
